import type { VendorDeviceProfile } from '../../types/vendors.js'

export const ciscoIosDevices: VendorDeviceProfile[] = [
  // --- ROUTERS ---
  {
    id: 'cisco-isr-1100-4p',
    vendor: 'cisco-ios',
    productLine: 'Cisco ISR 1100',
    model: 'ISR1100-4P',
    displayName: 'Cisco ISR 1100 4-Port',
    deviceType: 'router',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5', '17.6.6'],
    specs: {
      portCount: 4,
      sfpPorts: 1,
      wanPorts: 1,
      throughputGbps: 1,
      formFactor: 'desktop',
      managementProtocol: ['ssh', 'telnet', 'snmp', 'netconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'LAN interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'IOS-XE router for small branch deployments.',
  },
  {
    id: 'cisco-isr-4321',
    vendor: 'cisco-ios',
    productLine: 'Cisco ISR 4000',
    model: 'ISR4321',
    displayName: 'Cisco ISR 4321',
    deviceType: 'router',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 4,
      wanPorts: 2,
      throughputGbps: 0.1,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'LAN interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '50-100 Mbps throughput, 2x Service Module slots.',
  },
  {
    id: 'cisco-isr-4331',
    vendor: 'cisco-ios',
    productLine: 'Cisco ISR 4000',
    model: 'ISR4331',
    displayName: 'Cisco ISR 4331',
    deviceType: 'router',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 3,
      sfpPorts: 2,
      wanPorts: 2,
      throughputGbps: 0.3,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'LAN interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '100-300 Mbps throughput, 2x Service Module slots.',
  },
  {
    id: 'cisco-asr-1001x',
    vendor: 'cisco-ios',
    productLine: 'Cisco ASR 1000',
    model: 'ASR1001-X',
    displayName: 'Cisco ASR 1001-X',
    deviceType: 'router',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 6,
      sfpPlusPorts: 2,
      wanPorts: 2,
      throughputGbps: 20,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'LAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'WAN aggregation router, 20 Gbps throughput.',
  },

  // --- SWITCHES ---
  {
    id: 'cisco-cat-2960x-24ps-l',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 2960-X',
    model: 'WS-C2960X-24PS-L',
    displayName: 'Cisco Catalyst 2960X-24PS-L',
    deviceType: 'switch-l2',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['15.2(7)E9', '15.2(7)E8'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 370,
      sfpPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'telnet'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'cisco-cat-2960x-48fps-l',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 2960-X',
    model: 'WS-C2960X-48FPS-L',
    displayName: 'Cisco Catalyst 2960X-48FPS-L',
    deviceType: 'switch-l2',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['15.2(7)E9', '15.2(7)E8'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 740,
      sfpPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'telnet'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'cisco-cat-9200-24p',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 9200',
    model: 'C9200-24P',
    displayName: 'Cisco Catalyst 9200-24P',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 370,
      sfpPlusPorts: 4,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'cisco-cat-9300-48p',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 9300',
    model: 'C9300-48P',
    displayName: 'Cisco Catalyst 9300-48P',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 740,
      sfpPlusPorts: 4,
      layer3Capable: true,
      stackable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Advanced L3 stackable switch.',
  },
  {
    id: 'cisco-cat-9300-48uxm',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 9300',
    model: 'C9300-48UXM',
    displayName: 'Cisco Catalyst 9300-48UXM',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      portCount: 48,
      poePorts: 48,
      sfpPlusPorts: 4,
      layer3Capable: true,
      stackable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '48x mGig PoE ports (12x UPOE), supports high-power PoE devices.',
  },
  {
    id: 'cisco-cat-9500-24y4c',
    vendor: 'cisco-ios',
    productLine: 'Cisco Catalyst 9500',
    model: 'C9500-24Y4C',
    displayName: 'Cisco Catalyst 9500-24Y4C',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'cisco-ios-cli',
    firmwareVersions: ['17.12.3', '17.9.5'],
    specs: {
      sfp28Ports: 24,
      qsfpPorts: 4,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Core/distribution switch with 24x 25G and 4x 100G uplinks.',
  },
  {
    id: 'cisco-nexus-9336c-fx2',
    vendor: 'cisco-nxos',
    productLine: 'Cisco Nexus 9000',
    model: 'N9K-C9336C-FX2',
    displayName: 'Cisco Nexus 9336C-FX2',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-nxos-cli',
    firmwareVersions: ['10.4.3', '10.3.5'],
    specs: {
      qsfpPorts: 36,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'NX-OS leaf/spine switch, 36x 100G QSFP28 ports.',
  },
  {
    id: 'cisco-nexus-9508',
    vendor: 'cisco-nxos',
    productLine: 'Cisco Nexus 9000',
    model: 'N9K-C9508',
    displayName: 'Cisco Nexus 9508',
    deviceType: 'switch-l3',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-nxos-cli',
    firmwareVersions: ['10.4.3', '10.3.5'],
    specs: {
      layer3Capable: true,
      rackUnits: 7,
      formFactor: 'rack',
      managementProtocol: ['ssh', 'snmp', 'netconf', 'restconf'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_mode', label: 'Port Mode', type: 'select', required: false, affectsConfigOutput: true, options: [{ value: 'access', label: 'Access' }, { value: 'trunk', label: 'Trunk' }] },
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Modular NX-OS spine chassis, up to 576x 40GbE ports.',
  },

  // --- FIREWALLS (FTD) ---
  {
    id: 'cisco-ftd-1010',
    vendor: 'cisco-ios',
    productLine: 'Cisco Firepower 1000',
    model: 'FPR1010',
    displayName: 'Cisco Firepower 1010',
    deviceType: 'firewall',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ftd-xml',
    firmwareVersions: ['7.4.1', '7.2.8', '7.0.6'],
    specs: {
      portCount: 8,
      sfpPorts: 2,
      wanPorts: 1,
      throughputGbps: 0.65,
      idsIpsCapable: true,
      formFactor: 'desktop',
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'Outside interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'Interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Access Control Policy',
          description: 'FTD access control rules',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'block', label: 'Block' }] },
          ],
        },
      ],
    },
    notes: 'Cisco FTD OS, desktop form factor, 650 Mbps FW throughput.',
  },
  {
    id: 'cisco-ftd-2110',
    vendor: 'cisco-ios',
    productLine: 'Cisco Firepower 2100',
    model: 'FPR2110',
    displayName: 'Cisco Firepower 2110',
    deviceType: 'firewall',
    icon: 'cisco-ios',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'cisco-ftd-xml',
    firmwareVersions: ['7.4.1', '7.2.8'],
    specs: {
      portCount: 8,
      sfpPlusPorts: 4,
      wanPorts: 2,
      throughputGbps: 2.2,
      idsIpsCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'Outside interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'Interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Access Control Policy',
          description: 'FTD access control rules',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'block', label: 'Block' }] },
          ],
        },
      ],
    },
    notes: '2.2 Gbps FW throughput.',
  },
  {
    id: 'cisco-ftd-4115',
    vendor: 'cisco-ios',
    productLine: 'Cisco Firepower 4100',
    model: 'FPR4115',
    displayName: 'Cisco Firepower 4115',
    deviceType: 'firewall',
    icon: 'cisco-ios',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'cisco-ftd-xml',
    firmwareVersions: ['7.4.1', '7.2.8'],
    specs: {
      sfpPlusPorts: 12,
      qsfpPorts: 2,
      wanPorts: 2,
      throughputGbps: 20,
      idsIpsCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System hostname and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'Outside interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'Interface and subinterface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Access Control Policy',
          description: 'FTD access control rules',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'block', label: 'Block' }] },
          ],
        },
      ],
    },
    notes: '20 Gbps FW throughput, 12x SFP+ and 2x QSFP+ interfaces.',
  },
]
