import type { VendorDeviceProfile } from '../../types/vendors.js'

export const merakiDevices: VendorDeviceProfile[] = [
  // --- SECURITY APPLIANCES (MX) ---
  {
    id: 'meraki-mx67',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX67',
    displayName: 'Meraki MX67',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 10,
      wanPorts: 2,
      throughputGbps: 0.45,
      formFactor: 'desktop',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Up to 150 users. Desktop form factor.',
  },
  {
    id: 'meraki-mx68',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX68',
    displayName: 'Meraki MX68',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 10,
      poePorts: 2,
      wanPorts: 2,
      throughputGbps: 0.45,
      formFactor: 'desktop',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Includes 2x PoE LAN ports.',
  },
  {
    id: 'meraki-mx75',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX75',
    displayName: 'Meraki MX75',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 12,
      sfpPorts: 2,
      wanPorts: 2,
      throughputGbps: 1,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Up to 200 users.',
  },
  {
    id: 'meraki-mx85',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX85',
    displayName: 'Meraki MX85',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 12,
      sfpPorts: 4,
      wanPorts: 2,
      throughputGbps: 2,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Up to 500 users.',
  },
  {
    id: 'meraki-mx95',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX95',
    displayName: 'Meraki MX95',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 12,
      sfpPlusPorts: 2,
      wanPorts: 2,
      throughputGbps: 2,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Up to 2000 users.',
  },
  {
    id: 'meraki-mx250',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX250',
    displayName: 'Meraki MX250',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      portCount: 10,
      sfpPlusPorts: 8,
      wanPorts: 2,
      throughputGbps: 4,
      rackUnits: 2,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'meraki-mx450',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MX',
    model: 'MX450',
    displayName: 'Meraki MX450',
    deviceType: 'firewall',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['18.211.2', '18.107.12'],
    specs: {
      sfpPlusPorts: 12,
      wanPorts: 2,
      throughputGbps: 6,
      rackUnits: 2,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'L3 firewall rule configuration',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'allow', label: 'Allow' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Campus-scale security appliance.',
  },

  // --- SWITCHES (MS) ---
  {
    id: 'meraki-ms120-8fp',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS120-8FP',
    displayName: 'Meraki MS120-8FP',
    deviceType: 'switch-l2',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      portCount: 8,
      poePorts: 8,
      poeWatts: 124,
      sfpPorts: 2,
      formFactor: 'desktop',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'meraki-ms130-24p',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS130-24P',
    displayName: 'Meraki MS130-24P',
    deviceType: 'switch-l2',
    icon: 'cisco-meraki',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 370,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'meraki-ms130-48fp',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS130-48FP',
    displayName: 'Meraki MS130-48FP',
    deviceType: 'switch-l2',
    icon: 'cisco-meraki',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 740,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'meraki-ms225-48fp',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS225-48FP',
    displayName: 'Meraki MS225-48FP',
    deviceType: 'switch-l2',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 740,
      sfpPlusPorts: 4,
      stackable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Stackable L2 switch.',
  },
  {
    id: 'meraki-ms350-48fp',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS350-48FP',
    displayName: 'Meraki MS350-48FP',
    deviceType: 'switch-l3',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 740,
      sfpPlusPorts: 4,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port VLAN and PoE configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'meraki-ms410-32',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS410-32',
    displayName: 'Meraki MS410-32',
    deviceType: 'switch-l3',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      sfpPlusPorts: 32,
      qsfpPorts: 8,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Aggregation L3 switch.',
  },
  {
    id: 'meraki-ms425-32',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MS',
    model: 'MS425-32',
    displayName: 'Meraki MS425-32',
    deviceType: 'switch-l3',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['15.21.1', '15.20.1'],
    specs: {
      sfpPlusPorts: 32,
      qsfpPorts: 8,
      layer3Capable: true,
      multicastRoutingCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Advanced L3 campus core switch.',
  },

  // --- ACCESS POINTS (MR) ---
  {
    id: 'meraki-mr30h',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MR',
    model: 'MR30H',
    displayName: 'Meraki MR30H',
    deviceType: 'wireless-ap',
    icon: 'cisco-meraki',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['29.7.1', '29.6.1'],
    specs: {
      wirelessStandard: 'Wi-Fi 5 (802.11ac)',
      wirelessRadios: 2,
      portCount: 4,
      formFactor: 'wall-mount',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Hotel wall-plate AP with 4x GbE passthrough ports.',
  },
  {
    id: 'meraki-mr46',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MR',
    model: 'MR46',
    displayName: 'Meraki MR46',
    deviceType: 'wireless-ap',
    icon: 'cisco-meraki',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['29.7.1', '29.6.1'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Indoor enterprise Wi-Fi 6, up to 5.4 Gbps.',
  },
  {
    id: 'meraki-mr57',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MR',
    model: 'MR57',
    displayName: 'Meraki MR57',
    deviceType: 'wireless-ap',
    icon: 'cisco-meraki',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['29.7.1', '29.6.1'],
    specs: {
      wirelessStandard: 'Wi-Fi 6E (802.11ax) tri-band',
      wirelessRadios: 3,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Wi-Fi 6E high-density AP, up to 7.8 Gbps.',
  },
  {
    id: 'meraki-mr86',
    vendor: 'cisco-meraki',
    productLine: 'Meraki MR',
    model: 'MR86',
    displayName: 'Meraki MR86',
    deviceType: 'wireless-ap',
    icon: 'cisco-meraki',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'meraki-api-json',
    firmwareVersions: ['29.7.1', '29.6.1'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'outdoor',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Outdoor IP67 Wi-Fi 6 AP, up to 3.5 Gbps.',
  },
]
