import type { VendorDeviceProfile } from '../../types/vendors.js'

export const fortinetDevices: VendorDeviceProfile[] = [
  // --- FORTIGATE NGFW ---
  {
    id: 'fortinet-fg-40f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-40F',
    displayName: 'FortiGate 40F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8', '7.0.15'],
    specs: {
      portCount: 5,
      wanPorts: 1,
      throughputGbps: 5,
      idsIpsCapable: true,
      formFactor: 'desktop',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Branch NGFW, ~25 users. 700 Mbps IPS throughput.',
  },
  {
    id: 'fortinet-fg-60f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-60F',
    displayName: 'FortiGate 60F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8', '7.0.15'],
    specs: {
      portCount: 10,
      wanPorts: 2,
      throughputGbps: 10,
      idsIpsCapable: true,
      formFactor: 'desktop',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'SMB NGFW, ~50 users. 1 Gbps IPS throughput.',
  },
  {
    id: 'fortinet-fg-80f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-80F',
    displayName: 'FortiGate 80F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8'],
    specs: {
      portCount: 8,
      wanPorts: 2,
      sfpPorts: 2,
      throughputGbps: 10,
      idsIpsCapable: true,
      formFactor: 'desktop',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'fortinet-fg-100f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-100F',
    displayName: 'FortiGate 100F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8'],
    specs: {
      portCount: 22,
      sfpPorts: 4,
      wanPorts: 2,
      throughputGbps: 20,
      idsIpsCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: '3 Gbps IPS throughput.',
  },
  {
    id: 'fortinet-fg-200f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-200F',
    displayName: 'FortiGate 200F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8'],
    specs: {
      portCount: 18,
      sfpPlusPorts: 4,
      wanPorts: 2,
      throughputGbps: 27,
      idsIpsCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'fortinet-fg-600f',
    vendor: 'fortinet',
    productLine: 'FortiGate',
    model: 'FG-600F',
    displayName: 'FortiGate 600F',
    deviceType: 'firewall',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.8'],
    specs: {
      portCount: 18,
      sfpPlusPorts: 8,
      qsfpPorts: 2,
      wanPorts: 2,
      throughputGbps: 239,
      idsIpsCapable: true,
      rackUnits: 2,
      formFactor: 'rack',
      managementProtocol: ['https', 'ssh', 'snmp'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'System identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'Interfaces / VLANs',
          description: 'VLAN interface configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Policies',
          description: 'FortiGate firewall policy settings',
          fields: [
            { key: 'policy_name', label: 'Policy Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'deny', label: 'Deny' }] },
          ],
        },
      ],
    },
    notes: 'Data center NGFW with 2x QSFP+ (100G) ports.',
  },

  // --- FORTISWITCH ---
  {
    id: 'fortinet-fs-108f-poe',
    vendor: 'fortinet',
    productLine: 'FortiSwitch',
    model: 'FS-108F-POE',
    displayName: 'FortiSwitch 108F-POE',
    deviceType: 'switch-l2',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      portCount: 8,
      poePorts: 8,
      poeWatts: 130,
      sfpPorts: 2,
      formFactor: 'desktop',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'FortiLink-managed desktop switch.',
  },
  {
    id: 'fortinet-fs-124f-poe',
    vendor: 'fortinet',
    productLine: 'FortiSwitch',
    model: 'FS-124F-POE',
    displayName: 'FortiSwitch 124F-POE',
    deviceType: 'switch-l2',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 185,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'FortiLink-managed 1U switch.',
  },
  {
    id: 'fortinet-fs-248f-poe',
    vendor: 'fortinet',
    productLine: 'FortiSwitch',
    model: 'FS-248F-POE',
    displayName: 'FortiSwitch 248F-POE',
    deviceType: 'switch-l2',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 370,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'fortinet-fs-448f-poe',
    vendor: 'fortinet',
    productLine: 'FortiSwitch',
    model: 'FS-448F-POE',
    displayName: 'FortiSwitch 448F-POE',
    deviceType: 'switch-l3',
    icon: 'fortinet',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 760,
      sfpPlusPorts: 4,
      qsfpPorts: 4,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN and SVI configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'SVI Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_vlan', label: 'Access VLAN', type: 'number', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'L3 FortiSwitch with 4x QSFP+ uplinks.',
  },

  // --- FORTIAP ---
  {
    id: 'fortinet-fap-231f',
    vendor: 'fortinet',
    productLine: 'FortiAP',
    model: 'FAP-231F',
    displayName: 'FortiAP 231F',
    deviceType: 'wireless-ap',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Indoor Wi-Fi 6, dual-band, up to 1.8 Gbps.',
  },
  {
    id: 'fortinet-fap-431f',
    vendor: 'fortinet',
    productLine: 'FortiAP',
    model: 'FAP-431F',
    displayName: 'FortiAP 431F',
    deviceType: 'wireless-ap',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'High-density indoor Wi-Fi 6, up to 3.6 Gbps.',
  },
  {
    id: 'fortinet-fap-432f',
    vendor: 'fortinet',
    productLine: 'FortiAP',
    model: 'FAP-432F',
    displayName: 'FortiAP 432F',
    deviceType: 'wireless-ap',
    icon: 'fortinet',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'fortios-cli',
    firmwareVersions: ['7.4.3', '7.2.5'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'outdoor',
      managementProtocol: ['https', 'fortilink'],
    },
    configSchema: {
      sections: [
        {
          id: 'system',
          title: 'System',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Outdoor IP67 Wi-Fi 6 access point.',
  },
]
