import type { VendorDeviceProfile } from '../../types/vendors.js'

export const ubiquitiDevices: VendorDeviceProfile[] = [
  // --- GATEWAYS ---
  {
    id: 'unifi-udm-pro',
    vendor: 'ubiquiti',
    productLine: 'UniFi Gateway',
    model: 'UDM-Pro',
    displayName: 'UniFi Dream Machine Pro',
    deviceType: 'firewall',
    icon: 'ubiquiti',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['4.0.6', '4.0.5', '3.2.12'],
    specs: {
      portCount: 8,
      sfpPlusPorts: 2,
      wanPorts: 1,
      throughputGbps: 3.5,
      idsIpsCapable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'Basic firewall rule settings',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'drop', label: 'Drop' }, { value: 'reject', label: 'Reject' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-udm-se',
    vendor: 'ubiquiti',
    productLine: 'UniFi Gateway',
    model: 'UDM-SE',
    displayName: 'UniFi Dream Machine Special Edition',
    deviceType: 'firewall',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['3.2.12', '3.2.9'],
    specs: {
      portCount: 8,
      poePorts: 8,
      poeWatts: 60,
      sfpPlusPorts: 2,
      wanPorts: 1,
      throughputGbps: 2.5,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'Basic firewall rule settings',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'drop', label: 'Drop' }, { value: 'reject', label: 'Reject' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-uxg-pro',
    vendor: 'ubiquiti',
    productLine: 'UniFi Gateway',
    model: 'UXG-Pro',
    displayName: 'UniFi Express Gateway Pro',
    deviceType: 'firewall',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['3.2.12', '3.2.9'],
    specs: {
      portCount: 8,
      sfpPlusPorts: 4,
      wanPorts: 2,
      throughputGbps: 10,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'Basic firewall rule settings',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'drop', label: 'Drop' }, { value: 'reject', label: 'Reject' }] },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-usg-pro-4',
    vendor: 'ubiquiti',
    productLine: 'UniFi Gateway',
    model: 'USG-PRO-4',
    displayName: 'UniFi Security Gateway Pro 4',
    deviceType: 'firewall',
    icon: 'ubiquiti',
    releaseYear: 2017,
    eol: true,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['4.4.57', '4.4.56'],
    specs: {
      portCount: 4,
      wanPorts: 2,
      throughputGbps: 1,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity and management settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'UTC', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wan',
          title: 'WAN Configuration',
          description: 'WAN interface settings',
          fields: [
            { key: 'wan_type', label: 'WAN Type', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'dhcp', label: 'DHCP' }, { value: 'static', label: 'Static' }, { value: 'pppoe', label: 'PPPoE' }] },
            { key: 'wan_ip', label: 'WAN IP Address', type: 'ip', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'firewall-rules',
          title: 'Firewall Rules',
          description: 'Basic firewall rule settings',
          fields: [
            { key: 'rule_name', label: 'Rule Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'action', label: 'Action', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'accept', label: 'Accept' }, { value: 'drop', label: 'Drop' }, { value: 'reject', label: 'Reject' }] },
          ],
        },
      ],
    },
    notes: 'End-of-life product. Replaced by UDM-Pro series.',
  },

  // --- SWITCHES ---
  {
    id: 'unifi-us-8-60w',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch',
    model: 'US-8-60W',
    displayName: 'UniFi Switch 8 60W',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2019,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 8,
      poePorts: 8,
      poeWatts: 60,
      sfpPorts: 2,
      formFactor: 'desktop',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-usw-lite-8-poe',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch',
    model: 'USW-Lite-8-PoE',
    displayName: 'UniFi Switch Lite 8 PoE',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 8,
      poePorts: 4,
      poeWatts: 52,
      sfpPorts: 2,
      formFactor: 'desktop',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Fanless operation.',
  },
  {
    id: 'unifi-usw-lite-16-poe',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch',
    model: 'USW-Lite-16-PoE',
    displayName: 'UniFi Switch Lite 16 PoE',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 16,
      poePorts: 8,
      poeWatts: 45,
      sfpPorts: 2,
      formFactor: 'rack',
      rackUnits: 1,
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-usw-pro-24-poe',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Pro',
    model: 'USW-Pro-24-PoE',
    displayName: 'UniFi Switch Pro 24 PoE',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 195,
      sfpPlusPorts: 2,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-usw-pro-48-poe',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Pro',
    model: 'USW-Pro-48-PoE',
    displayName: 'UniFi Switch Pro 48 PoE',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 600,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
  },
  {
    id: 'unifi-usw-pro-48',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Pro',
    model: 'USW-Pro-48',
    displayName: 'UniFi Switch Pro 48',
    deviceType: 'switch-l2',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 48,
      sfpPlusPorts: 4,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Non-PoE model.',
  },
  {
    id: 'unifi-usw-enterprise-24',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Enterprise',
    model: 'USW-Enterprise-24-PoE',
    displayName: 'UniFi Switch Enterprise 24 PoE',
    deviceType: 'switch-l3',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 24,
      poePorts: 24,
      poeWatts: 400,
      sfpPlusPorts: 2,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '2.5GbE ports with L3 routing capability.',
  },
  {
    id: 'unifi-usw-enterprise-48',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Enterprise',
    model: 'USW-Enterprise-48-PoE',
    displayName: 'UniFi Switch Enterprise 48 PoE',
    deviceType: 'switch-l3',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 48,
      poePorts: 48,
      poeWatts: 600,
      sfpPlusPorts: 4,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '2.5GbE ports with L3 routing capability.',
  },
  {
    id: 'unifi-usw-aggregation',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch',
    model: 'USW-Aggregation',
    displayName: 'UniFi Switch Aggregation',
    deviceType: 'switch-l3',
    icon: 'ubiquiti',
    releaseYear: 2020,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      sfpPlusPorts: 8,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Aggregation switch with 8x SFP+ ports only.',
  },
  {
    id: 'unifi-usw-pro-max-24',
    vendor: 'ubiquiti',
    productLine: 'UniFi Switch Pro Max',
    model: 'USW-Pro-Max-24',
    displayName: 'UniFi Switch Pro Max 24',
    deviceType: 'switch-l3',
    icon: 'ubiquiti',
    releaseYear: 2023,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      portCount: 24,
      poePorts: 24,
      sfpPlusPorts: 2,
      sfp28Ports: 2,
      layer3Capable: true,
      rackUnits: 1,
      formFactor: 'rack',
      cloudManaged: true,
      managementProtocol: ['https', 'ssh'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'vlans',
          title: 'VLANs',
          description: 'VLAN configuration',
          fields: [
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: true, affectsConfigOutput: true },
            { key: 'vlan_name', label: 'VLAN Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'subnet', label: 'Subnet (CIDR)', type: 'cidr', required: false, affectsConfigOutput: true },
          ],
        },
        {
          id: 'switch-ports',
          title: 'Switch Ports',
          description: 'Per-port configuration',
          fields: [
            { key: 'port_profile', label: 'Port Profile', type: 'text', required: false, affectsConfigOutput: true },
            { key: 'poe_enabled', label: 'PoE Enabled', type: 'boolean', defaultValue: true, required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: '2.5GbE PoE access ports plus 2x SFP+ and 2x SFP28 (25G) uplinks.',
  },

  // --- ACCESS POINTS ---
  {
    id: 'unifi-u6-lite',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-Lite',
    displayName: 'UniFi U6 Lite',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Dual-band 2.4 + 5 GHz, up to 1.5 Gbps.',
  },
  {
    id: 'unifi-u6-pro',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-Pro',
    displayName: 'UniFi U6 Pro',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Dual-band 2.4 + 5 GHz, up to 4.8 Gbps.',
  },
  {
    id: 'unifi-u6-long-range',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-LR',
    displayName: 'UniFi U6 Long-Range',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2021,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Extended range up to 600 ft.',
  },
  {
    id: 'unifi-u6-enterprise',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-Enterprise',
    displayName: 'UniFi U6 Enterprise',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6E (802.11ax) tri-band',
      wirelessRadios: 3,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Wi-Fi 6E tri-band, up to 6 Gbps, 2.5GbE uplink.',
  },
  {
    id: 'unifi-u6-enterprise-iw',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-Enterprise-IW',
    displayName: 'UniFi U6 Enterprise In-Wall',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6E (802.11ax) tri-band',
      wirelessRadios: 3,
      portCount: 2,
      formFactor: 'in-wall',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'In-wall form factor with 2x GbE passthrough ports.',
  },
  {
    id: 'unifi-u6-mesh',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'U6-Mesh',
    displayName: 'UniFi U6 Mesh',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2022,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.6.57', '6.6.55'],
    specs: {
      wirelessStandard: 'Wi-Fi 6 (802.11ax)',
      wirelessRadios: 2,
      formFactor: 'outdoor',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'wpa3', label: 'WPA3' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Outdoor IP67-rated Wi-Fi 6 access point with mesh support.',
  },
  {
    id: 'unifi-uap-ac-pro',
    vendor: 'ubiquiti',
    productLine: 'UniFi Access Point',
    model: 'UAP-AC-PRO',
    displayName: 'UniFi UAP-AC-Pro',
    deviceType: 'wireless-ap',
    icon: 'ubiquiti',
    releaseYear: 2016,
    ndaaCompliant: true,
    configFormat: 'unifi-network-app',
    firmwareVersions: ['6.0.22', '6.0.21'],
    specs: {
      wirelessStandard: 'Wi-Fi 5 (802.11ac)',
      wirelessRadios: 2,
      formFactor: 'ceiling',
      cloudManaged: true,
      managementProtocol: ['https'],
    },
    configSchema: {
      sections: [
        {
          id: 'network-identity',
          title: 'Network Identity',
          description: 'Basic device identity settings',
          fields: [
            { key: 'hostname', label: 'Hostname', type: 'text', required: true, affectsConfigOutput: true },
          ],
        },
        {
          id: 'wireless',
          title: 'Wireless',
          description: 'Wireless network settings',
          fields: [
            { key: 'ssid_name', label: 'SSID Name', type: 'text', required: true, affectsConfigOutput: true },
            { key: 'security', label: 'Security Mode', type: 'select', required: true, affectsConfigOutput: true, options: [{ value: 'wpa2', label: 'WPA2' }, { value: 'open', label: 'Open' }] },
            { key: 'passphrase', label: 'Passphrase', type: 'password', required: false, affectsConfigOutput: true },
            { key: 'vlan_id', label: 'VLAN ID', type: 'number', required: false, affectsConfigOutput: true },
          ],
        },
      ],
    },
    notes: 'Legacy Wi-Fi 5 AP, up to 1.3 Gbps.',
  },
]
