export const DEVICE_CATEGORIES = {
  'Network Infrastructure': ['firewall', 'switch-l2', 'switch-l3', 'router', 'wireless-ap', 'patch-panel'],
  'End Devices': ['workstation', 'server', 'printer', 'voip-phone', 'nas'],
  'Security & Monitoring': ['camera', 'firewall-edge'],
  'Industrial': ['plc', 'sensor', 'hmi'],
  'Other': ['internet'],
} as const

export const DEFAULT_VLANS = {
  DATA: 10,
  VOICE: 20,
  GUEST: 30,
  SERVERS: 40,
  DMZ: 50,
  MGMT: 99,
} as const

export const PROTOCOL_LABELS: Record<string, string> = {
  'mpls': 'MPLS',
  'sd-wan': 'SD-WAN',
  'site-to-site-vpn': 'S2S-VPN',
  'ssl-vpn': 'SSL-VPN',
  'gre-tunnel': 'GRE',
  'wireguard': 'WireGuard',
  'ospf': 'OSPF',
  'bgp': 'BGP',
  'eigrp': 'EIGRP',
  'rip': 'RIP',
  'static-route': 'Static',
  'profinet': 'PROFINET',
  'ethernet-ip': 'EtherNet/IP',
  'modbus-tcp': 'Modbus TCP',
  'bacnet': 'BACnet',
  'dnp3': 'DNP3',
  'iscsi': 'iSCSI',
  'fibre-channel': 'FC',
  'nfs': 'NFS',
  'smb': 'SMB',
  'snmp': 'SNMP',
  'netflow': 'NetFlow',
  'syslog': 'Syslog',
  'none': 'None',
  'custom': 'Custom',
}

export const PROTOCOL_DESCRIPTIONS: Record<string, string> = {
  'mpls': 'Multiprotocol Label Switching — carrier-grade WAN transport',
  'sd-wan': 'Software-Defined WAN — intelligent traffic steering across multiple links',
  'site-to-site-vpn': 'IPsec site-to-site VPN tunnel providing encrypted connectivity between two fixed endpoints',
  'ssl-vpn': 'SSL/TLS VPN for remote user access',
  'gre-tunnel': 'Generic Routing Encapsulation — point-to-point tunnel protocol',
  'wireguard': 'Modern high-performance VPN protocol',
  'ospf': 'Open Shortest Path First — link-state interior routing protocol',
  'bgp': 'Border Gateway Protocol — exterior routing protocol used for internet routing',
  'eigrp': 'Enhanced Interior Gateway Routing Protocol — Cisco advanced distance-vector protocol',
  'rip': 'Routing Information Protocol — distance-vector routing protocol',
  'static-route': 'Manually configured routing entries',
  'profinet': 'Industrial Ethernet standard for real-time automation',
  'ethernet-ip': 'EtherNet/IP — industrial protocol using standard Ethernet',
  'modbus-tcp': 'Modbus over TCP/IP — serial communication protocol for industrial devices',
  'bacnet': 'Building Automation and Control Network protocol',
  'dnp3': 'Distributed Network Protocol — SCADA and utility automation',
  'iscsi': 'Internet Small Computer Systems Interface — block storage over IP',
  'fibre-channel': 'High-speed network technology for storage area networks',
  'nfs': 'Network File System — distributed file system protocol',
  'smb': 'Server Message Block — Windows file and printer sharing protocol',
  'snmp': 'Simple Network Management Protocol — device monitoring and management',
  'netflow': 'Cisco network traffic analysis and monitoring protocol',
  'syslog': 'Standard protocol for message logging',
  'none': 'No specific protocol assigned',
  'custom': 'Custom or proprietary protocol',
}

export const PROTOCOL_GROUPS: Record<string, string[]> = {
  'WAN / Tunneling': ['mpls', 'sd-wan', 'site-to-site-vpn', 'ssl-vpn', 'gre-tunnel', 'wireguard'],
  'Routing': ['ospf', 'bgp', 'eigrp', 'rip', 'static-route'],
  'Industrial': ['profinet', 'ethernet-ip', 'modbus-tcp', 'bacnet', 'dnp3'],
  'Storage': ['iscsi', 'fibre-channel', 'nfs', 'smb'],
  'Management': ['snmp', 'netflow', 'syslog'],
  'Other': ['none', 'custom'],
}

export const DEVICE_DISPLAY_NAMES: Record<string, string> = {
  'firewall': 'Firewall',
  'switch-l2': 'L2 Switch',
  'switch-l3': 'L3 Switch',
  'router': 'Router',
  'server': 'Server',
  'workstation': 'Workstation',
  'printer': 'Printer',
  'wireless-ap': 'Wireless AP',
  'camera': 'Camera',
  'voip-phone': 'VoIP Phone',
  'nas': 'NAS',
  'internet': 'Internet',
  'plc': 'PLC',
  'sensor': 'Sensor',
  'patch-panel': 'Patch Panel',
  'hmi': 'HMI',
  'firewall-edge': 'Edge Firewall',
}
