export const DEVICE_CATEGORIES = {
  'Network Core': ['firewall', 'firewall-edge', 'router', 'switch-l3', 'load-balancer', 'wan-optimizer', 'content-filter'],
  'LAN Switching': ['switch-l2', 'patch-panel', 'network-tap', 'packet-broker'],
  'Wireless': ['wireless-ap', 'wireless-controller', 'cellular-gateway', 'satellite-modem', 'lte-router', 'sd-wan-appliance'],
  'Servers & Compute': ['server', 'workstation', 'thin-client', 'hypervisor', 'virtual-machine', 'container-host', 'gpu-server', 'blade-chassis', 'blade-server', 'server-rack'],
  'Storage': ['nas', 'san-switch', 'tape-library', 'backup-appliance', 'object-storage'],
  'Security': ['siem-server', 'log-server', 'dns-server', 'radius-server', 'proxy-server', 'ddos-scrubber'],
  'Unified Comms': ['voip-phone', 'pbx-server', 'sbc', 'voip-gateway', 'video-conference-unit'],
  'Industrial OT': ['plc', 'hmi', 'sensor', 'rtu', 'dcs', 'sis-controller', 'historian-server', 'scada-server', 'ied', 'protocol-converter', 'data-diode'],
  'Physical Security': ['camera', 'nvr', 'dvr', 'video-analytics-server', 'license-plate-reader', 'intrusion-panel', 'fire-panel-gateway'],
  'Access Control': ['ac-server', 'ac-controller', 'ac-reader', 'ac-door-hardware', 'ac-intercom', 'ac-biometric', 'ac-key-pad', 'ac-visitor-kiosk', 'ac-elevator-ctrl', 'ac-turnstile'],
  'Power & Environmental': ['ups', 'pdu', 'environmental-sensor', 'generator', 'cooling-unit'],
  'Smart Building': ['bas-controller', 'hvac-controller', 'lighting-controller', 'energy-meter', 'bacnet-router', 'elevator-controller'],
  'Healthcare': ['medical-device', 'infusion-pump', 'patient-monitor', 'emr-server', 'pacs-server', 'nurse-call-server'],
  'Cloud & Internet': ['internet', 'isp-handoff', 'cloud-aws', 'cloud-azure', 'cloud-gcp', 'cloud-m365', 'cloud-saas', 'colocation-fabric'],
} as const

export const DEFAULT_VLANS = {
  DATA: 10,
  VOICE: 20,
  GUEST: 30,
  SERVERS: 40,
  DMZ: 50,
  MGMT: 99,
} as const

export const PROTOCOL_LABELS: Record<string, string> = {
  'mpls': 'MPLS',
  'sd-wan': 'SD-WAN',
  'site-to-site-vpn': 'S2S-VPN',
  'ssl-vpn': 'SSL-VPN',
  'gre-tunnel': 'GRE',
  'wireguard': 'WireGuard',
  'ospf': 'OSPF',
  'bgp': 'BGP',
  'eigrp': 'EIGRP',
  'rip': 'RIP',
  'static-route': 'Static',
  'profinet': 'PROFINET',
  'ethernet-ip': 'EtherNet/IP',
  'modbus-tcp': 'Modbus TCP',
  'bacnet': 'BACnet',
  'dnp3': 'DNP3',
  'iscsi': 'iSCSI',
  'fibre-channel': 'FC',
  'nfs': 'NFS',
  'smb': 'SMB',
  'snmp': 'SNMP',
  'netflow': 'NetFlow',
  'syslog': 'Syslog',
  'none': 'None',
  'custom': 'Custom',
}

export const PROTOCOL_DESCRIPTIONS: Record<string, string> = {
  'mpls': 'Multiprotocol Label Switching — carrier-grade WAN transport',
  'sd-wan': 'Software-Defined WAN — intelligent traffic steering across multiple links',
  'site-to-site-vpn': 'IPsec site-to-site VPN tunnel providing encrypted connectivity between two fixed endpoints',
  'ssl-vpn': 'SSL/TLS VPN for remote user access',
  'gre-tunnel': 'Generic Routing Encapsulation — point-to-point tunnel protocol',
  'wireguard': 'Modern high-performance VPN protocol',
  'ospf': 'Open Shortest Path First — link-state interior routing protocol',
  'bgp': 'Border Gateway Protocol — exterior routing protocol used for internet routing',
  'eigrp': 'Enhanced Interior Gateway Routing Protocol — Cisco advanced distance-vector protocol',
  'rip': 'Routing Information Protocol — distance-vector routing protocol',
  'static-route': 'Manually configured routing entries',
  'profinet': 'Industrial Ethernet standard for real-time automation',
  'ethernet-ip': 'EtherNet/IP — industrial protocol using standard Ethernet',
  'modbus-tcp': 'Modbus over TCP/IP — serial communication protocol for industrial devices',
  'bacnet': 'Building Automation and Control Network protocol',
  'dnp3': 'Distributed Network Protocol — SCADA and utility automation',
  'iscsi': 'Internet Small Computer Systems Interface — block storage over IP',
  'fibre-channel': 'High-speed network technology for storage area networks',
  'nfs': 'Network File System — distributed file system protocol',
  'smb': 'Server Message Block — Windows file and printer sharing protocol',
  'snmp': 'Simple Network Management Protocol — device monitoring and management',
  'netflow': 'Cisco network traffic analysis and monitoring protocol',
  'syslog': 'Standard protocol for message logging',
  'none': 'No specific protocol assigned',
  'custom': 'Custom or proprietary protocol',
}

export const PROTOCOL_GROUPS: Record<string, string[]> = {
  'WAN / Tunneling': ['mpls', 'sd-wan', 'site-to-site-vpn', 'ssl-vpn', 'gre-tunnel', 'wireguard'],
  'Routing': ['ospf', 'bgp', 'eigrp', 'rip', 'static-route'],
  'Industrial': ['profinet', 'ethernet-ip', 'modbus-tcp', 'bacnet', 'dnp3'],
  'Storage': ['iscsi', 'fibre-channel', 'nfs', 'smb'],
  'Management': ['snmp', 'netflow', 'syslog'],
  'Other': ['none', 'custom'],
}

export const DEVICE_DISPLAY_NAMES: Record<string, string> = {
  // Original devices
  'firewall': 'Firewall',
  'switch-l2': 'L2 Switch',
  'switch-l3': 'L3 Switch',
  'router': 'Router',
  'server': 'Server',
  'workstation': 'Workstation',
  'printer': 'Printer',
  'wireless-ap': 'Wireless AP',
  'camera': 'Camera',
  'voip-phone': 'VoIP Phone',
  'nas': 'NAS',
  'internet': 'Internet',
  'plc': 'PLC',
  'sensor': 'Sensor',
  'patch-panel': 'Patch Panel',
  'hmi': 'HMI',
  'firewall-edge': 'Edge Firewall',
  'ac-server': 'AC Server',
  'ac-controller': 'AC Controller',
  'ac-reader': 'Card Reader',
  'ac-door-hardware': 'Door Hardware',
  'ac-intercom': 'Intercom',
  'ac-biometric': 'Biometric Reader',
  'ac-key-pad': 'Keypad',
  'ac-visitor-kiosk': 'Visitor Kiosk',
  'ac-elevator-ctrl': 'Elevator Ctrl',
  'ac-turnstile': 'Turnstile',
  // Network Infrastructure
  'load-balancer': 'Load Balancer',
  'wan-optimizer': 'WAN Optimizer',
  'packet-broker': 'Packet Broker',
  'network-tap': 'Network TAP',
  'content-filter': 'Content Filter',
  'ddos-scrubber': 'DDoS Scrubber',
  'dns-server': 'DNS Server',
  'radius-server': 'RADIUS Server',
  'proxy-server': 'Proxy Server',
  'siem-server': 'SIEM',
  'log-server': 'Log Server',
  // Wireless/Cellular
  'wireless-controller': 'Wireless Controller',
  'cellular-gateway': 'Cellular Gateway',
  'cellular-modem': 'Cellular Modem',
  'satellite-modem': 'Satellite Modem',
  'lte-router': 'LTE Router',
  'sd-wan-appliance': 'SD-WAN Appliance',
  // Compute
  'hypervisor': 'Hypervisor',
  'virtual-machine': 'Virtual Machine',
  'container-host': 'Container Host',
  'blade-chassis': 'Blade Chassis',
  'blade-server': 'Blade Server',
  'server-rack': 'Server Rack',
  'thin-client': 'Thin Client',
  'gpu-server': 'GPU Server',
  // Storage
  'san-switch': 'SAN Switch',
  'tape-library': 'Tape Library',
  'backup-appliance': 'Backup Appliance',
  'object-storage': 'Object Storage',
  // Power
  'ups': 'UPS',
  'pdu': 'PDU',
  'environmental-sensor': 'Env Sensor',
  'generator': 'Generator',
  'cooling-unit': 'Cooling Unit',
  // UC
  'pbx-server': 'PBX Server',
  'sbc': 'SBC',
  'voip-gateway': 'VoIP Gateway',
  'video-conference-unit': 'Video Conf',
  // OT additions
  'rtu': 'RTU',
  'dcs': 'DCS',
  'sis-controller': 'SIS Controller',
  'historian-server': 'Historian',
  'scada-server': 'SCADA Server',
  'ied': 'IED',
  'protocol-converter': 'Protocol Conv.',
  'data-diode': 'Data Diode',
  // Physical Security additions
  'nvr': 'NVR',
  'dvr': 'DVR',
  'video-analytics-server': 'Video Analytics',
  'license-plate-reader': 'LPR Camera',
  'intrusion-panel': 'Intrusion Panel',
  'fire-panel-gateway': 'Fire Panel GW',
  // Smart Building
  'bas-controller': 'BAS Controller',
  'hvac-controller': 'HVAC Controller',
  'lighting-controller': 'Lighting Ctrl',
  'energy-meter': 'Energy Meter',
  'bacnet-router': 'BACnet Router',
  'elevator-controller': 'Elevator Ctrl',
  // Healthcare
  'medical-device': 'Medical Device',
  'infusion-pump': 'Infusion Pump',
  'patient-monitor': 'Patient Monitor',
  'emr-server': 'EMR Server',
  'pacs-server': 'PACS Server',
  'nurse-call-server': 'Nurse Call',
  // Cloud
  'cloud-aws': 'AWS Cloud',
  'cloud-azure': 'Azure Cloud',
  'cloud-gcp': 'GCP',
  'cloud-m365': 'Microsoft 365',
  'cloud-saas': 'SaaS',
  'colocation-fabric': 'Colo Fabric',
  'isp-handoff': 'ISP Handoff',
}

export const CONNECTION_TYPE_LABELS: Record<string, string> = {
  'ethernet-copper': 'Ethernet (Copper)',
  'ethernet-fiber': 'Ethernet (Fiber)',
  'ethernet-sfp': 'Ethernet (SFP)',
  'ethernet-dac': 'Ethernet (DAC)',
  'wifi': 'Wi-Fi',
  'wifi-backhaul': 'Wi-Fi Backhaul',
  'trunk-8021q': '802.1Q Trunk',
  'access-port': 'Access Port',
  'site-to-site-ipsec': 'IPsec S2S VPN',
  'wireguard': 'WireGuard VPN',
  'ssl-vpn-client': 'SSL VPN Client',
  'mpls': 'MPLS',
  'sd-wan': 'SD-WAN',
  'ospf': 'OSPF',
  'bgp': 'BGP',
  'eigrp': 'EIGRP',
  'routed-static': 'Static Route',
  'vlan-routing': 'VLAN Routing (SVI)',
  'fibre-channel': 'Fibre Channel',
  'iscsi': 'iSCSI',
  'profinet': 'PROFINET',
  'modbus-tcp': 'Modbus TCP',
  'bacnet': 'BACnet',
  'dnp3': 'DNP3',
  'opc-ua': 'OPC UA',
  'iec-61850': 'IEC 61850',
  'poe': 'PoE',
  'poe-plus': 'PoE+',
  'poe-bt': 'PoE++',
  'fortilink': 'FortiLink',
  'unifi-adopt': 'UniFi Adopt',
  'internet-access': 'Internet',
  'direct-connect': 'Direct Connect',
  'cloud-vpn': 'Cloud VPN',
  'osdp': 'OSDP',
  'snmp': 'SNMP',
  'ssh': 'SSH',
  'gre-tunnel': 'GRE Tunnel',
  'vxlan': 'VXLAN',
  'site-to-site-ssl': 'SSL S2S VPN',
  'l2tp': 'L2TP',
  'ipsec-dmvpn': 'DMVPN',
  'qinq': 'Q-in-Q',
  'wiegand': 'Wiegand',
  'serial-console': 'Serial',
  'oob-console': 'OOB Console',
}

export const CONNECTION_TYPE_GROUPS: Record<string, string[]> = {
  'Physical / L2': ['ethernet-copper', 'ethernet-fiber', 'ethernet-sfp', 'ethernet-dac', 'serial-console', 'oob-console'],
  'Wireless': ['wifi', 'wifi-backhaul'],
  'VLAN / Segmentation': ['trunk-8021q', 'access-port', 'qinq', 'vlan-routing'],
  'VPN / Tunneling': ['site-to-site-ipsec', 'wireguard', 'ssl-vpn-client', 'l2tp', 'gre-tunnel', 'vxlan', 'ipsec-dmvpn', 'site-to-site-ssl', 'cloud-vpn'],
  'WAN / Routing': ['mpls', 'sd-wan', 'ospf', 'bgp', 'eigrp', 'routed-static'],
  'Industrial': ['profinet', 'modbus-tcp', 'bacnet', 'dnp3', 'opc-ua', 'iec-61850'],
  'Storage': ['fibre-channel', 'iscsi'],
  'Power': ['poe', 'poe-plus', 'poe-bt'],
  'Management': ['snmp', 'ssh', 'fortilink', 'unifi-adopt'],
  'Cloud / Internet': ['internet-access', 'direct-connect', 'peering'],
  'Physical Security': ['osdp', 'wiegand'],
}
