import { FastifyPluginAsync } from 'fastify'
import { z } from 'zod'
import { TopologySnapshotSchema, ALL_NETWORK_DEVICES, ALL_AC_DEVICES } from '@gridhive/shared'
import type { VendorDeviceProfile } from '@gridhive/shared'
import { generateUniFiJson } from '../../lib/configExport/generators/UniFiJsonGenerator.js'

const ALL_PROFILES: VendorDeviceProfile[] = [...ALL_NETWORK_DEVICES, ...ALL_AC_DEVICES]

const ExportRequestSchema = z.object({
  topology: TopologySnapshotSchema,
  deviceId: z.string(),
  profileId: z.string(),
})

const configExportModule: FastifyPluginAsync = async (fastify) => {
  // GET /export/profiles — list all vendor device profiles
  fastify.get('/profiles', async (_request, reply) => {
    return reply.send({ data: ALL_PROFILES })
  })

  // GET /export/profiles/:vendor — profiles for a specific vendor
  fastify.get('/profiles/:vendor', async (request, reply) => {
    const { vendor } = request.params as { vendor: string }
    const profiles = ALL_PROFILES.filter((p) => p.vendor === vendor)
    if (profiles.length === 0) {
      return reply.status(404).send({ error: `No profiles found for vendor: ${vendor}` })
    }
    return reply.send({ data: profiles })
  })

  // POST /export/device-config — generate a config file for a device node
  fastify.post('/device-config', async (request, reply) => {
    const parsed = ExportRequestSchema.safeParse(request.body)
    if (!parsed.success) {
      return reply.status(400).send({ error: 'Invalid request', details: parsed.error.flatten() })
    }

    const { topology, deviceId, profileId } = parsed.data

    const device = topology.nodes.find((n) => n.id === deviceId)
    if (!device) {
      return reply.status(404).send({ error: `Device not found: ${deviceId}` })
    }

    const profile = ALL_PROFILES.find((p) => p.id === profileId)
    if (!profile) {
      return reply.status(404).send({ error: `Profile not found: ${profileId}` })
    }

    try {
      let result

      if (profile.configFormat === 'unifi-json' || profile.configFormat === 'unifi-network-app') {
        result = generateUniFiJson(topology, device, profile)
      } else {
        // Generic summary for formats without a dedicated generator yet
        result = {
          deviceId: device.id,
          vendor: profile.vendor,
          format: profile.configFormat,
          filename: `${device.data.hostname || device.id}-config.txt`,
          content: generateGenericSummary(device, profile),
          warnings: ['Full config generation not yet available for this format. This is a configuration summary.'],
          instructions: `Review and apply this configuration summary to your ${profile.vendor} ${profile.model} device.`,
        }
      }

      return reply.send({ data: result })
    } catch (err) {
      fastify.log.error(err)
      return reply.status(500).send({ error: 'Config export failed' })
    }
  })
}

function generateGenericSummary(device: { id: string; data: Record<string, unknown> }, profile: VendorDeviceProfile): string {
  const d = device.data
  const lines: string[] = [
    `# Configuration Summary`,
    `# Generated by Gridhive`,
    `# Device: ${d['label'] || d['hostname'] || device.id}`,
    `# Vendor: ${profile.vendor}`,
    `# Model: ${profile.model}`,
    `# Format: ${profile.configFormat}`,
    ``,
    `## Device Properties`,
    `hostname: ${d['hostname'] || 'N/A'}`,
    `IP Address: ${d['ipAddress'] || 'N/A'}`,
    `Subnet Mask: ${d['subnetMask'] || 'N/A'}`,
    `VLAN: ${d['vlanId'] || 'N/A'}`,
    `Role: ${d['role'] || 'N/A'}`,
    ``,
  ]

  if (profile.configSchema?.sections) {
    for (const section of profile.configSchema.sections) {
      lines.push(`## ${section.title}`)
      for (const field of section.fields) {
        const val = d[field.key]
        if (val !== undefined && val !== null && val !== '') {
          lines.push(`${field.label}: ${val}`)
        } else if (field.defaultValue !== undefined) {
          lines.push(`${field.label}: ${field.defaultValue} (default)`)
        }
      }
      lines.push('')
    }
  }

  return lines.join('\n')
}

export default configExportModule
