import type { NetForgeTemplate } from '../../types/index.js'

export const airGappedClassifiedTemplate: NetForgeTemplate = {
  id: 'system-air-gapped-classified',
  slug: 'air-gapped-classified',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Air-Gapped Classified Network',
    category: 'specialty',
    description: 'Air-gapped classified network with complete isolation from all external networks. Data transfer only via controlled media and data diode.',
    tags: ['air-gap', 'classified', 'cmmc', 'nist-csf', 'no-internet'],
    difficulty: 'advanced',
    deviceCount: 10,
    thumbnail: '',
    notes: 'Air-gapped networks rely on physical security and administrative controls. No internet node is present by design. Validation info messages about missing internet path are expected. VLANs: 1=CLASSIFIED (192.168.200.0/24), 99=MGMT.',
    validationExpected: 'warnings',
  },
  topology: {
    nodes: [
      {
        id: 'node-airgap-core-sw',
        type: 'switch-l3',
        position: { x: 600, y: 200 },
        data: {
          hostname: 'sw-core-classified',
          label: 'Core Switch',
          deviceType: 'switch-l3',
          ipAddress: '192.168.200.1/24',
          subnet: '192.168.200.0/24',
          interVlanRouting: true,
          vlanTrunkPorts: [1, 99],
        },
      },
      {
        id: 'node-airgap-acc-sw1',
        type: 'switch-l2',
        position: { x: 300, y: 400 },
        data: {
          hostname: 'sw-acc-classified-01',
          label: 'Access Switch 1',
          deviceType: 'switch-l2',
          ipAddress: '192.168.200.10/24',
          subnet: '192.168.200.0/24',
          vlanTrunkPorts: [1, 99],
        },
      },
      {
        id: 'node-airgap-acc-sw2',
        type: 'switch-l2',
        position: { x: 900, y: 400 },
        data: {
          hostname: 'sw-acc-classified-02',
          label: 'Access Switch 2',
          deviceType: 'switch-l2',
          ipAddress: '192.168.200.11/24',
          subnet: '192.168.200.0/24',
          vlanTrunkPorts: [1, 99],
        },
      },
      {
        id: 'node-airgap-ws1',
        type: 'workstation',
        position: { x: 100, y: 600 },
        data: {
          hostname: 'ws-cleared-01',
          label: 'Workstation 1',
          deviceType: 'workstation',
          ipAddress: '192.168.200.20/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'cleared-personnel',
        },
      },
      {
        id: 'node-airgap-ws2',
        type: 'workstation',
        position: { x: 280, y: 600 },
        data: {
          hostname: 'ws-cleared-02',
          label: 'Workstation 2',
          deviceType: 'workstation',
          ipAddress: '192.168.200.21/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'cleared-personnel',
        },
      },
      {
        id: 'node-airgap-ws3',
        type: 'workstation',
        position: { x: 760, y: 600 },
        data: {
          hostname: 'ws-cleared-03',
          label: 'Workstation 3',
          deviceType: 'workstation',
          ipAddress: '192.168.200.22/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'cleared-personnel',
        },
      },
      {
        id: 'node-airgap-ws4',
        type: 'workstation',
        position: { x: 940, y: 600 },
        data: {
          hostname: 'ws-cleared-04',
          label: 'Workstation 4',
          deviceType: 'workstation',
          ipAddress: '192.168.200.23/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'cleared-personnel',
        },
      },
      {
        id: 'node-airgap-file-srv',
        type: 'server',
        position: { x: 400, y: 200 },
        data: {
          hostname: 'srv-classified-files',
          label: 'File Server',
          deviceType: 'server',
          ipAddress: '192.168.200.50/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'classified-files',
          os: 'Windows Server 2022',
        },
      },
      {
        id: 'node-airgap-print-srv',
        type: 'server',
        position: { x: 600, y: 400 },
        data: {
          hostname: 'srv-print',
          label: 'Print Server',
          deviceType: 'server',
          ipAddress: '192.168.200.51/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'print-server',
        },
      },
      {
        id: 'node-airgap-auth-srv',
        type: 'server',
        position: { x: 800, y: 200 },
        data: {
          hostname: 'srv-auth',
          label: 'Auth Server',
          deviceType: 'server',
          ipAddress: '192.168.200.52/24',
          subnet: '192.168.200.0/24',
          defaultGateway: '192.168.200.1',
          vlanId: 1,
          role: 'auth-server',
        },
      },
      {
        id: 'node-airgap-data-diode',
        type: 'server',
        position: { x: 1100, y: 200 },
        data: {
          hostname: 'data-diode-01',
          label: 'Data Diode',
          deviceType: 'server',
          ipAddress: '192.168.200.60/24',
          subnet: '192.168.200.0/24',
          vlanId: 1,
          role: 'data-diode',
          notes: 'One-way data transfer device - output side faces classified network, input side is isolated',
        },
      },
      {
        id: 'node-airgap-media-station',
        type: 'workstation',
        position: { x: 1100, y: 400 },
        data: {
          hostname: 'ws-media-transfer',
          label: 'Media Transfer Station',
          deviceType: 'workstation',
          ipAddress: '192.168.200.70/24',
          subnet: '192.168.200.0/24',
          vlanId: 1,
          role: 'media-transfer',
          notes: 'Controlled removable media ingest station with mandatory AV scanning',
        },
      },
      {
        id: 'node-airgap-crypto',
        type: 'server',
        position: { x: 400, y: 0 },
        data: {
          hostname: 'crypto-device-01',
          label: 'Crypto Device',
          deviceType: 'server',
          ipAddress: '192.168.200.80/24',
          subnet: '192.168.200.0/24',
          vlanId: 1,
          role: 'crypto-device',
          notes: 'Type 1 encryption device for at-rest and in-transit data protection',
        },
      },
    ],
    edges: [
      { id: 'airgap-e1', source: 'node-airgap-core-sw', target: 'node-airgap-acc-sw1', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [1, 99], uplink: true, status: 'active' } },
      { id: 'airgap-e2', source: 'node-airgap-core-sw', target: 'node-airgap-acc-sw2', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [1, 99], uplink: true, status: 'active' } },
      { id: 'airgap-e3', source: 'node-airgap-core-sw', target: 'node-airgap-file-srv', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e4', source: 'node-airgap-core-sw', target: 'node-airgap-auth-srv', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e5', source: 'node-airgap-core-sw', target: 'node-airgap-print-srv', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e6', source: 'node-airgap-core-sw', target: 'node-airgap-data-diode', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, label: 'Data Diode Output - One Way', status: 'active' } },
      { id: 'airgap-e7', source: 'node-airgap-core-sw', target: 'node-airgap-media-station', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, label: 'Controlled Media Ingest', status: 'active' } },
      { id: 'airgap-e8', source: 'node-airgap-core-sw', target: 'node-airgap-crypto', data: { mediaType: 'fiber', speed: '1G', vlanTag: 1, label: 'Encrypted Link', status: 'active' } },
      { id: 'airgap-e9', source: 'node-airgap-acc-sw1', target: 'node-airgap-ws1', data: { mediaType: 'copper', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e10', source: 'node-airgap-acc-sw1', target: 'node-airgap-ws2', data: { mediaType: 'copper', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e11', source: 'node-airgap-acc-sw2', target: 'node-airgap-ws3', data: { mediaType: 'copper', speed: '1G', vlanTag: 1, status: 'active' } },
      { id: 'airgap-e12', source: 'node-airgap-acc-sw2', target: 'node-airgap-ws4', data: { mediaType: 'copper', speed: '1G', vlanTag: 1, status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.8 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'airgap-sim-1',
      name: 'Workstation can reach File Server',
      type: 'reachability',
      sourceNodeId: 'node-airgap-ws1',
      targetNodeId: 'node-airgap-file-srv',
      expectedResult: 'pass',
      description: 'Cleared personnel workstations on VLAN 1 can reach the classified file server',
    },
    {
      id: 'airgap-sim-2',
      name: 'Workstation can reach Auth Server',
      type: 'reachability',
      sourceNodeId: 'node-airgap-ws1',
      targetNodeId: 'node-airgap-auth-srv',
      expectedResult: 'pass',
      description: 'Workstations must be able to authenticate against the local auth server',
    },
    {
      id: 'airgap-sim-3',
      name: 'Media Transfer Station is isolated from core network',
      type: 'isolation',
      sourceNodeId: 'node-airgap-media-station',
      targetNodeId: 'node-airgap-file-srv',
      expectedResult: 'pass',
      description: 'The media transfer station should not have direct access to classified file servers until media has been inspected',
    },
    {
      id: 'airgap-sim-4',
      name: 'Data Diode output does not reach core classified zone',
      type: 'isolation',
      sourceNodeId: 'node-airgap-data-diode',
      targetNodeId: 'node-airgap-auth-srv',
      expectedResult: 'pass',
      description: 'Data diode enforces one-way data flow only; the diode output path cannot initiate connections back into the classified core',
    },
  ],
}
