import type { NetForgeTemplate } from '../../types/index.js'

export const broadcastMediaStudioTemplate: NetForgeTemplate = {
  id: 'system-broadcast-media-studio',
  slug: 'broadcast-media-studio',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Broadcast Media Studio Network',
    category: 'specialty',
    description: 'Professional broadcast media production network with SMPTE ST 2110 IP video, Dante/AES67 audio, and strict isolation between production and corporate IT networks.',
    tags: ['broadcast', 'media', 'production', 'smpte', 'dante'],
    difficulty: 'intermediate',
    deviceCount: 13,
    thumbnail: '',
    notes: 'VLANs: 10=VIDEO (192.168.50.0/24), 20=AUDIO (192.168.51.0/24), 30=CONTROL (192.168.52.0/24), 40=CORPORATE (192.168.100.0/24). Production network is physically and logically isolated from corporate IT.',
    validationExpected: 'pass',
  },
  topology: {
    nodes: [
      {
        id: 'node-bcast-internet',
        type: 'internet',
        position: { x: 1000, y: 0 },
        data: { hostname: 'INTERNET', label: 'Internet', deviceType: 'internet' },
      },
      {
        id: 'node-bcast-fw',
        type: 'firewall',
        position: { x: 1000, y: 150 },
        data: {
          hostname: 'fw-broadcast',
          label: 'Firewall',
          deviceType: 'firewall',
          ipAddress: '192.168.100.1/24',
          subnet: '192.168.100.0/24',
          vlanId: 40,
          role: 'gateway',
        },
      },
      {
        id: 'node-bcast-it-sw',
        type: 'switch-l2',
        position: { x: 1000, y: 300 },
        data: {
          hostname: 'sw-it-core',
          label: 'IT Core Switch',
          deviceType: 'switch-l2',
          ipAddress: '192.168.100.2/24',
          subnet: '192.168.100.0/24',
          vlanTrunkPorts: [40],
        },
      },
      {
        id: 'node-bcast-corp-ws1',
        type: 'workstation',
        position: { x: 860, y: 450 },
        data: {
          hostname: 'ws-corp-01',
          label: 'Corporate Workstation 1',
          deviceType: 'workstation',
          ipAddress: '192.168.100.20/24',
          subnet: '192.168.100.0/24',
          defaultGateway: '192.168.100.1',
          vlanId: 40,
        },
      },
      {
        id: 'node-bcast-corp-ws2',
        type: 'workstation',
        position: { x: 1000, y: 450 },
        data: {
          hostname: 'ws-corp-02',
          label: 'Corporate Workstation 2',
          deviceType: 'workstation',
          ipAddress: '192.168.100.21/24',
          subnet: '192.168.100.0/24',
          defaultGateway: '192.168.100.1',
          vlanId: 40,
        },
      },
      {
        id: 'node-bcast-prod-sw',
        type: 'switch-l3',
        position: { x: 400, y: 150 },
        data: {
          hostname: 'sw-production-core',
          label: 'Production Core Switch',
          deviceType: 'switch-l3',
          ipAddress: '192.168.50.1/24',
          subnet: '192.168.50.0/24',
          interVlanRouting: true,
          vlanTrunkPorts: [10, 20, 30],
          notes: 'Production switch has NO uplink to IT or internet',
        },
      },
      {
        id: 'node-bcast-media-nas',
        type: 'nas',
        position: { x: 100, y: 300 },
        data: {
          hostname: 'nas-media-asset',
          label: 'Media Asset Server',
          deviceType: 'nas',
          ipAddress: '192.168.50.10/24',
          subnet: '192.168.50.0/24',
          vlanId: 10,
          role: 'media-asset',
        },
      },
      {
        id: 'node-bcast-playout',
        type: 'server',
        position: { x: 300, y: 300 },
        data: {
          hostname: 'srv-playout',
          label: 'Playout Server',
          deviceType: 'server',
          ipAddress: '192.168.50.11/24',
          subnet: '192.168.50.0/24',
          vlanId: 10,
          role: 'playout',
        },
      },
      {
        id: 'node-bcast-ingest',
        type: 'server',
        position: { x: 500, y: 300 },
        data: {
          hostname: 'srv-ingest',
          label: 'Ingest Server',
          deviceType: 'server',
          ipAddress: '192.168.50.12/24',
          subnet: '192.168.50.0/24',
          vlanId: 10,
          role: 'ingest',
        },
      },
      {
        id: 'node-bcast-vid-router',
        type: 'server',
        position: { x: 700, y: 300 },
        data: {
          hostname: 'srv-video-router',
          label: 'Production Router',
          deviceType: 'server',
          ipAddress: '192.168.52.10/24',
          subnet: '192.168.52.0/24',
          vlanId: 30,
          role: 'video-router',
          notes: 'Software-defined video router for SMPTE ST 2110 signal routing',
        },
      },
      {
        id: 'node-bcast-audio-mixer',
        type: 'server',
        position: { x: 300, y: 450 },
        data: {
          hostname: 'srv-dante-audio',
          label: 'IP Audio Mixer',
          deviceType: 'server',
          ipAddress: '192.168.51.10/24',
          subnet: '192.168.51.0/24',
          vlanId: 20,
          role: 'dante-audio',
        },
      },
      {
        id: 'node-bcast-mcast-gw',
        type: 'server',
        position: { x: 600, y: 450 },
        data: {
          hostname: 'srv-multicast-gw',
          label: 'Multicast Gateway',
          deviceType: 'server',
          ipAddress: '192.168.50.20/24',
          subnet: '192.168.50.0/24',
          vlanId: 10,
          role: 'multicast-gateway',
          notes: 'PIM-SM multicast gateway for SMPTE ST 2110 multicast streams',
        },
      },
      {
        id: 'node-bcast-edit-ws1',
        type: 'workstation',
        position: { x: 100, y: 450 },
        data: {
          hostname: 'ws-edit-01',
          label: 'Edit Workstation 1',
          deviceType: 'workstation',
          ipAddress: '192.168.50.30/24',
          subnet: '192.168.50.0/24',
          defaultGateway: '192.168.50.1',
          vlanId: 10,
          role: 'video-editor',
          os: 'macOS',
        },
      },
      {
        id: 'node-bcast-edit-ws2',
        type: 'workstation',
        position: { x: 100, y: 600 },
        data: {
          hostname: 'ws-edit-02',
          label: 'Edit Workstation 2',
          deviceType: 'workstation',
          ipAddress: '192.168.50.31/24',
          subnet: '192.168.50.0/24',
          defaultGateway: '192.168.50.1',
          vlanId: 10,
          role: 'video-editor',
          os: 'macOS',
        },
      },
      {
        id: 'node-bcast-edit-ws3',
        type: 'workstation',
        position: { x: 300, y: 600 },
        data: {
          hostname: 'ws-edit-03',
          label: 'Edit Workstation 3',
          deviceType: 'workstation',
          ipAddress: '192.168.50.32/24',
          subnet: '192.168.50.0/24',
          defaultGateway: '192.168.50.1',
          vlanId: 10,
          role: 'video-editor',
          os: 'macOS',
        },
      },
    ],
    edges: [
      { id: 'bcast-e1', source: 'node-bcast-internet', target: 'node-bcast-fw', data: { mediaType: 'wan', speed: 'variable', label: 'WAN', status: 'active' } },
      { id: 'bcast-e2', source: 'node-bcast-fw', target: 'node-bcast-it-sw', data: { mediaType: 'fiber', speed: '1G', vlanTag: 40, status: 'active' } },
      { id: 'bcast-e3', source: 'node-bcast-it-sw', target: 'node-bcast-corp-ws1', data: { mediaType: 'copper', speed: '1G', vlanTag: 40, status: 'active' } },
      { id: 'bcast-e4', source: 'node-bcast-it-sw', target: 'node-bcast-corp-ws2', data: { mediaType: 'copper', speed: '1G', vlanTag: 40, status: 'active' } },
      { id: 'bcast-e5', source: 'node-bcast-prod-sw', target: 'node-bcast-media-nas', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e6', source: 'node-bcast-prod-sw', target: 'node-bcast-playout', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e7', source: 'node-bcast-prod-sw', target: 'node-bcast-ingest', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e8', source: 'node-bcast-prod-sw', target: 'node-bcast-vid-router', data: { mediaType: 'fiber', speed: '10G', vlanTag: 30, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e9', source: 'node-bcast-prod-sw', target: 'node-bcast-audio-mixer', data: { mediaType: 'fiber', speed: '1G', vlanTag: 20, label: 'Dante/AES67', status: 'active' } },
      { id: 'bcast-e10', source: 'node-bcast-prod-sw', target: 'node-bcast-mcast-gw', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, status: 'active' } },
      { id: 'bcast-e11', source: 'node-bcast-prod-sw', target: 'node-bcast-edit-ws1', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e12', source: 'node-bcast-prod-sw', target: 'node-bcast-edit-ws2', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
      { id: 'bcast-e13', source: 'node-bcast-prod-sw', target: 'node-bcast-edit-ws3', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, label: 'SMPTE ST 2110', status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.8 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'bcast-sim-1',
      name: 'Editor can reach Media Asset Server',
      type: 'reachability',
      sourceNodeId: 'node-bcast-edit-ws1',
      targetNodeId: 'node-bcast-media-nas',
      expectedResult: 'pass',
      description: 'Edit workstations on VLAN 10 can access the media asset storage via the production core switch',
    },
    {
      id: 'bcast-sim-2',
      name: 'Playout Server can reach Ingest Server',
      type: 'reachability',
      sourceNodeId: 'node-bcast-playout',
      targetNodeId: 'node-bcast-ingest',
      expectedResult: 'pass',
      description: 'Playout and ingest servers on VLAN 10 communicate over the production network for live ingest to playout workflows',
    },
    {
      id: 'bcast-sim-3',
      name: 'Production network is isolated from internet',
      type: 'isolation',
      sourceNodeId: 'node-bcast-playout',
      targetNodeId: 'node-bcast-internet',
      expectedResult: 'pass',
      description: 'The production network has no connection to the IT firewall or internet; the production core switch has no uplink to corporate IT',
    },
    {
      id: 'bcast-sim-4',
      name: 'Corporate workstation isolated from Playout Server',
      type: 'isolation',
      sourceNodeId: 'node-bcast-corp-ws1',
      targetNodeId: 'node-bcast-playout',
      expectedResult: 'pass',
      description: 'Corporate workstations on VLAN 40 must not be able to reach production servers on VLAN 10',
    },
  ],
}
