import type { NetForgeTemplate } from '../../types/index.js'

export const financialTradingFloorTemplate: NetForgeTemplate = {
  id: 'system-financial-trading-floor',
  slug: 'financial-trading-floor',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Financial Trading Floor Network',
    category: 'specialty',
    description: 'High-performance low-latency trading floor network with PCI-DSS compliant segmentation, redundant core switches in LACP active-active, FIX gateway, and strict isolation between trading and corporate zones.',
    tags: ['trading', 'finance', 'pci-dss', 'soc2', 'low-latency'],
    difficulty: 'advanced',
    deviceCount: 14,
    thumbnail: '',
    notes: 'VLANs: 10=TRADING (10.50.10.0/24), 20=CORPORATE (10.50.20.0/24), 30=MARKET-DATA (10.50.30.0/24), 40=MGMT (10.50.99.0/24). Trading VLAN is isolated from direct internet access.',
    validationExpected: 'pass',
  },
  topology: {
    nodes: [
      {
        id: 'node-trade-internet',
        type: 'internet',
        position: { x: 600, y: 0 },
        data: { hostname: 'INTERNET', label: 'Internet', deviceType: 'internet' },
      },
      {
        id: 'node-trade-corp-fw',
        type: 'firewall',
        position: { x: 600, y: 150 },
        data: {
          hostname: 'fw-corp-01',
          label: 'Corporate Firewall',
          deviceType: 'firewall',
          ipAddress: '10.50.99.1/24',
          subnet: '10.50.99.0/24',
          vlanId: 99,
          role: 'gateway',
        },
      },
      {
        id: 'node-trade-colo-router',
        type: 'router',
        position: { x: 200, y: 150 },
        data: {
          hostname: 'rtr-colo-01',
          label: 'Colo Router',
          deviceType: 'router',
          ipAddress: '10.50.99.5/24',
          subnet: '10.50.99.0/24',
          role: 'colo-router',
        },
      },
      {
        id: 'node-trade-core-sw-a',
        type: 'switch-l3',
        position: { x: 400, y: 300 },
        data: {
          hostname: 'sw-core-trade-a',
          label: 'Core Switch A',
          deviceType: 'switch-l3',
          ipAddress: '10.50.99.10/24',
          subnet: '10.50.99.0/24',
          interVlanRouting: true,
          vlanTrunkPorts: [10, 20, 30, 40],
        },
      },
      {
        id: 'node-trade-core-sw-b',
        type: 'switch-l3',
        position: { x: 800, y: 300 },
        data: {
          hostname: 'sw-core-trade-b',
          label: 'Core Switch B',
          deviceType: 'switch-l3',
          ipAddress: '10.50.99.11/24',
          subnet: '10.50.99.0/24',
          interVlanRouting: true,
          vlanTrunkPorts: [10, 20, 30, 40],
        },
      },
      {
        id: 'node-trade-market-data1',
        type: 'server',
        position: { x: 100, y: 500 },
        data: {
          hostname: 'srv-mktdata-01',
          label: 'Market Data Server 1',
          deviceType: 'server',
          ipAddress: '10.50.30.10/24',
          subnet: '10.50.30.0/24',
          vlanId: 30,
          role: 'market-data',
        },
      },
      {
        id: 'node-trade-market-data2',
        type: 'server',
        position: { x: 300, y: 500 },
        data: {
          hostname: 'srv-mktdata-02',
          label: 'Market Data Server 2',
          deviceType: 'server',
          ipAddress: '10.50.30.11/24',
          subnet: '10.50.30.0/24',
          vlanId: 30,
          role: 'market-data',
        },
      },
      {
        id: 'node-trade-engine1',
        type: 'server',
        position: { x: 500, y: 500 },
        data: {
          hostname: 'srv-trade-engine-01',
          label: 'Trading Engine 1',
          deviceType: 'server',
          ipAddress: '10.50.10.10/24',
          subnet: '10.50.10.0/24',
          vlanId: 10,
          role: 'trading-engine',
        },
      },
      {
        id: 'node-trade-engine2',
        type: 'server',
        position: { x: 700, y: 500 },
        data: {
          hostname: 'srv-trade-engine-02',
          label: 'Trading Engine 2',
          deviceType: 'server',
          ipAddress: '10.50.10.11/24',
          subnet: '10.50.10.0/24',
          vlanId: 10,
          role: 'trading-engine',
        },
      },
      {
        id: 'node-trade-risk-srv',
        type: 'server',
        position: { x: 900, y: 500 },
        data: {
          hostname: 'srv-risk-01',
          label: 'Risk Server',
          deviceType: 'server',
          ipAddress: '10.50.10.20/24',
          subnet: '10.50.10.0/24',
          vlanId: 10,
          role: 'risk-server',
        },
      },
      {
        id: 'node-trade-fix-gw',
        type: 'server',
        position: { x: 100, y: 300 },
        data: {
          hostname: 'srv-fix-gw',
          label: 'FIX Gateway',
          deviceType: 'server',
          ipAddress: '10.50.10.30/24',
          subnet: '10.50.10.0/24',
          vlanId: 10,
          role: 'fix-gateway',
        },
      },
      {
        id: 'node-trade-time-sync',
        type: 'server',
        position: { x: 1100, y: 300 },
        data: {
          hostname: 'srv-time-sync',
          label: 'Time Sync Server',
          deviceType: 'server',
          ipAddress: '10.50.99.50/24',
          subnet: '10.50.99.0/24',
          vlanId: 40,
          role: 'time-sync',
          notes: 'GPS-disciplined NTP/PTP IEEE 1588 grandmaster clock',
        },
      },
      {
        id: 'node-trade-compliance',
        type: 'server',
        position: { x: 1100, y: 500 },
        data: {
          hostname: 'srv-compliance',
          label: 'Compliance Server',
          deviceType: 'server',
          ipAddress: '10.50.20.50/24',
          subnet: '10.50.20.0/24',
          vlanId: 20,
          role: 'compliance',
        },
      },
      {
        id: 'node-trade-corp-sw',
        type: 'switch-l2',
        position: { x: 800, y: 500 },
        data: {
          hostname: 'sw-corporate',
          label: 'Corporate Switch',
          deviceType: 'switch-l2',
          ipAddress: '10.50.20.2/24',
          subnet: '10.50.20.0/24',
          vlanTrunkPorts: [20, 40],
        },
      },
      {
        id: 'node-trade-ws1',
        type: 'workstation',
        position: { x: 600, y: 700 },
        data: {
          hostname: 'ws-trader-01',
          label: 'Trader Workstation 1',
          deviceType: 'workstation',
          ipAddress: '10.50.20.11/24',
          subnet: '10.50.20.0/24',
          defaultGateway: '10.50.20.1',
          vlanId: 20,
        },
      },
      {
        id: 'node-trade-ws2',
        type: 'workstation',
        position: { x: 740, y: 700 },
        data: {
          hostname: 'ws-trader-02',
          label: 'Trader Workstation 2',
          deviceType: 'workstation',
          ipAddress: '10.50.20.12/24',
          subnet: '10.50.20.0/24',
          defaultGateway: '10.50.20.1',
          vlanId: 20,
        },
      },
      {
        id: 'node-trade-ws3',
        type: 'workstation',
        position: { x: 880, y: 700 },
        data: {
          hostname: 'ws-trader-03',
          label: 'Trader Workstation 3',
          deviceType: 'workstation',
          ipAddress: '10.50.20.13/24',
          subnet: '10.50.20.0/24',
          defaultGateway: '10.50.20.1',
          vlanId: 20,
        },
      },
      {
        id: 'node-trade-ws4',
        type: 'workstation',
        position: { x: 1020, y: 700 },
        data: {
          hostname: 'ws-trader-04',
          label: 'Trader Workstation 4',
          deviceType: 'workstation',
          ipAddress: '10.50.20.14/24',
          subnet: '10.50.20.0/24',
          defaultGateway: '10.50.20.1',
          vlanId: 20,
        },
      },
    ],
    edges: [
      { id: 'trade-e1', source: 'node-trade-internet', target: 'node-trade-corp-fw', data: { mediaType: 'wan', speed: 'variable', label: 'WAN', status: 'active' } },
      { id: 'trade-e2', source: 'node-trade-colo-router', target: 'node-trade-core-sw-a', data: { mediaType: 'wan', speed: '10G', protocol: 'mpls', label: 'Co-Lo Private Line', status: 'active' } },
      { id: 'trade-e3', source: 'node-trade-corp-fw', target: 'node-trade-core-sw-a', data: { mediaType: 'fiber', speed: '10G', trunkVlans: [10, 20, 30, 40], uplink: true, status: 'active' } },
      { id: 'trade-e4', source: 'node-trade-corp-fw', target: 'node-trade-core-sw-b', data: { mediaType: 'fiber', speed: '10G', trunkVlans: [10, 20, 30, 40], uplink: true, status: 'active' } },
      { id: 'trade-e5', source: 'node-trade-core-sw-a', target: 'node-trade-core-sw-b', data: { mediaType: 'fiber', speed: '10G', label: 'LACP-Active-Active', trunkVlans: [10, 20, 30, 40], status: 'active' } },
      { id: 'trade-e6', source: 'node-trade-core-sw-a', target: 'node-trade-fix-gw', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, status: 'active' } },
      { id: 'trade-e7', source: 'node-trade-core-sw-a', target: 'node-trade-market-data1', data: { mediaType: 'fiber', speed: '10G', vlanTag: 30, status: 'active' } },
      { id: 'trade-e8', source: 'node-trade-core-sw-a', target: 'node-trade-market-data2', data: { mediaType: 'fiber', speed: '10G', vlanTag: 30, status: 'active' } },
      { id: 'trade-e9', source: 'node-trade-core-sw-a', target: 'node-trade-engine1', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, status: 'active' } },
      { id: 'trade-e10', source: 'node-trade-core-sw-b', target: 'node-trade-engine2', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, status: 'active' } },
      { id: 'trade-e11', source: 'node-trade-core-sw-b', target: 'node-trade-risk-srv', data: { mediaType: 'fiber', speed: '10G', vlanTag: 10, status: 'active' } },
      { id: 'trade-e12', source: 'node-trade-core-sw-b', target: 'node-trade-time-sync', data: { mediaType: 'fiber', speed: '1G', vlanTag: 40, label: 'GPS-NTP PTP IEEE 1588', status: 'active' } },
      { id: 'trade-e13', source: 'node-trade-core-sw-a', target: 'node-trade-time-sync', data: { mediaType: 'fiber', speed: '1G', vlanTag: 40, label: 'GPS-NTP PTP IEEE 1588', status: 'active' } },
      { id: 'trade-e14', source: 'node-trade-core-sw-b', target: 'node-trade-corp-sw', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [20, 40], status: 'active' } },
      { id: 'trade-e15', source: 'node-trade-corp-sw', target: 'node-trade-ws1', data: { mediaType: 'copper', speed: '1G', vlanTag: 20, status: 'active' } },
      { id: 'trade-e16', source: 'node-trade-corp-sw', target: 'node-trade-ws2', data: { mediaType: 'copper', speed: '1G', vlanTag: 20, status: 'active' } },
      { id: 'trade-e17', source: 'node-trade-corp-sw', target: 'node-trade-ws3', data: { mediaType: 'copper', speed: '1G', vlanTag: 20, status: 'active' } },
      { id: 'trade-e18', source: 'node-trade-corp-sw', target: 'node-trade-ws4', data: { mediaType: 'copper', speed: '1G', vlanTag: 20, status: 'active' } },
      { id: 'trade-e19', source: 'node-trade-corp-sw', target: 'node-trade-compliance', data: { mediaType: 'copper', speed: '1G', vlanTag: 20, status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.75 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'trade-sim-1',
      name: 'Trader workstation can reach Trading Engine',
      type: 'reachability',
      sourceNodeId: 'node-trade-ws1',
      targetNodeId: 'node-trade-engine1',
      expectedResult: 'pass',
      description: 'Trader workstations on VLAN 20 can reach trading engines on VLAN 10 through core switches',
    },
    {
      id: 'trade-sim-2',
      name: 'Trading Engine can reach FIX Gateway',
      type: 'reachability',
      sourceNodeId: 'node-trade-engine1',
      targetNodeId: 'node-trade-fix-gw',
      expectedResult: 'pass',
      description: 'Trading engines on VLAN 10 can send orders through the FIX gateway to the co-lo router',
    },
    {
      id: 'trade-sim-3',
      name: 'Trading VLAN is isolated from internet',
      type: 'isolation',
      sourceNodeId: 'node-trade-engine1',
      targetNodeId: 'node-trade-internet',
      expectedResult: 'pass',
      description: 'Trading engines on VLAN 10 must not have direct internet access; all external connectivity goes through the co-lo private line',
    },
    {
      id: 'trade-sim-4',
      name: 'Corporate zone isolated from Trading Engine',
      type: 'isolation',
      sourceNodeId: 'node-trade-ws1',
      targetNodeId: 'node-trade-engine1',
      expectedResult: 'pass',
      description: 'Corporate workstations on VLAN 20 should not directly reach trading engines on VLAN 10 per PCI-DSS segmentation requirements',
    },
    {
      id: 'trade-sim-5',
      name: 'Trading servers can reach Time Sync Server',
      type: 'reachability',
      sourceNodeId: 'node-trade-engine1',
      targetNodeId: 'node-trade-time-sync',
      expectedResult: 'pass',
      description: 'Trading infrastructure must synchronize clocks with the GPS-disciplined time server for regulatory audit trail requirements',
    },
  ],
}
