import type { NetForgeTemplate } from '../../types/index.js'

export const maritimeVesselTemplate: NetForgeTemplate = {
  id: 'system-maritime-vessel',
  slug: 'maritime-vessel',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Maritime Vessel Network',
    category: 'specialty',
    description: 'SOLAS-compliant maritime vessel network with segregated bridge, engine room, crew, and passenger networks. VSAT primary communications with 4G backup. Navigation and GMDSS safety systems isolated.',
    tags: ['maritime', 'vessel', 'navigation', 'nist-csf', 'solas'],
    difficulty: 'advanced',
    deviceCount: 13,
    thumbnail: '',
    notes: 'VLANs: 10=BRIDGE (10.10.10.0/24), 20=ENGINE (10.10.20.0/24), 30=CREW (10.10.30.0/24), 40=PASSENGER (10.10.40.0/24), 50=COMMS (10.10.50.0/24), 99=MGMT. Passenger network must not reach bridge or engine systems.',
    validationExpected: 'warnings',
  },
  topology: {
    nodes: [
      {
        id: 'node-vessel-fw',
        type: 'firewall',
        position: { x: 600, y: 150 },
        data: {
          hostname: 'fw-vessel-01',
          label: 'Vessel Firewall',
          deviceType: 'firewall',
          ipAddress: '10.10.99.1/24',
          subnet: '10.10.99.0/24',
          vlanId: 99,
          role: 'gateway',
        },
      },
      {
        id: 'node-vessel-vsat',
        type: 'router',
        position: { x: 400, y: 0 },
        data: {
          hostname: 'rtr-vsat',
          label: 'VSAT Gateway',
          deviceType: 'router',
          ipAddress: '10.10.50.10/24',
          subnet: '10.10.50.0/24',
          vlanId: 50,
          role: 'vsat-gateway',
        },
      },
      {
        id: 'node-vessel-4g',
        type: 'router',
        position: { x: 800, y: 0 },
        data: {
          hostname: 'rtr-4g-gw',
          label: '4G Gateway',
          deviceType: 'router',
          ipAddress: '10.10.50.11/24',
          subnet: '10.10.50.0/24',
          vlanId: 50,
          role: '4g-gateway',
        },
      },
      {
        id: 'node-vessel-bridge-sw',
        type: 'switch-l2',
        position: { x: 200, y: 300 },
        data: {
          hostname: 'sw-bridge',
          label: 'Bridge Network Switch',
          deviceType: 'switch-l2',
          ipAddress: '10.10.10.1/24',
          subnet: '10.10.10.0/24',
          vlanTrunkPorts: [10, 99],
        },
      },
      {
        id: 'node-vessel-engine-sw',
        type: 'switch-l2',
        position: { x: 400, y: 300 },
        data: {
          hostname: 'sw-engine-room',
          label: 'Engine Room Switch',
          deviceType: 'switch-l2',
          ipAddress: '10.10.20.1/24',
          subnet: '10.10.20.0/24',
          vlanTrunkPorts: [20, 99],
        },
      },
      {
        id: 'node-vessel-crew-sw',
        type: 'switch-l2',
        position: { x: 600, y: 300 },
        data: {
          hostname: 'sw-crew',
          label: 'Crew Network Switch',
          deviceType: 'switch-l2',
          ipAddress: '10.10.30.1/24',
          subnet: '10.10.30.0/24',
          vlanTrunkPorts: [30, 99],
        },
      },
      {
        id: 'node-vessel-pax-sw',
        type: 'switch-l2',
        position: { x: 800, y: 300 },
        data: {
          hostname: 'sw-passenger',
          label: 'Passenger Network Switch',
          deviceType: 'switch-l2',
          ipAddress: '10.10.40.1/24',
          subnet: '10.10.40.0/24',
          vlanTrunkPorts: [40, 99],
        },
      },
      {
        id: 'node-vessel-nav-srv',
        type: 'server',
        position: { x: 100, y: 450 },
        data: {
          hostname: 'srv-navigation',
          label: 'Navigation Server',
          deviceType: 'server',
          ipAddress: '10.10.10.10/24',
          subnet: '10.10.10.0/24',
          vlanId: 10,
          role: 'navigation',
          notes: 'ECDIS and GNSS navigation system',
        },
      },
      {
        id: 'node-vessel-ais',
        type: 'server',
        position: { x: 200, y: 450 },
        data: {
          hostname: 'srv-ais',
          label: 'AIS Transponder',
          deviceType: 'server',
          ipAddress: '10.10.10.11/24',
          subnet: '10.10.10.0/24',
          vlanId: 10,
          role: 'ais-transponder',
        },
      },
      {
        id: 'node-vessel-vdr',
        type: 'server',
        position: { x: 300, y: 450 },
        data: {
          hostname: 'srv-vdr',
          label: 'VDR Server',
          deviceType: 'server',
          ipAddress: '10.10.10.12/24',
          subnet: '10.10.10.0/24',
          vlanId: 10,
          role: 'vdr',
          notes: 'Voyage Data Recorder',
        },
      },
      {
        id: 'node-vessel-gmdss',
        type: 'server',
        position: { x: 0, y: 450 },
        data: {
          hostname: 'srv-gmdss',
          label: 'GMDSS Radio',
          deviceType: 'server',
          ipAddress: '10.10.10.13/24',
          subnet: '10.10.10.0/24',
          vlanId: 10,
          role: 'gmdss',
          notes: 'Global Maritime Distress and Safety System radio',
        },
      },
      {
        id: 'node-vessel-engine-ctrl',
        type: 'server',
        position: { x: 400, y: 450 },
        data: {
          hostname: 'srv-engine-ctrl',
          label: 'Engine Control Server',
          deviceType: 'server',
          ipAddress: '10.10.20.10/24',
          subnet: '10.10.20.0/24',
          vlanId: 20,
          role: 'engine-control',
        },
      },
      {
        id: 'node-vessel-pax-ap1',
        type: 'wireless-ap',
        position: { x: 700, y: 450 },
        data: {
          hostname: 'ap-passenger-01',
          label: 'Passenger AP 1',
          deviceType: 'wireless-ap',
          ipAddress: '10.10.40.20/24',
          subnet: '10.10.40.0/24',
          vlanId: 40,
          poe: true,
        },
      },
      {
        id: 'node-vessel-pax-ap2',
        type: 'wireless-ap',
        position: { x: 900, y: 450 },
        data: {
          hostname: 'ap-passenger-02',
          label: 'Passenger AP 2',
          deviceType: 'wireless-ap',
          ipAddress: '10.10.40.21/24',
          subnet: '10.10.40.0/24',
          vlanId: 40,
          poe: true,
        },
      },
    ],
    edges: [
      { id: 'vessel-e1', source: 'node-vessel-vsat', target: 'node-vessel-fw', data: { mediaType: 'wan', speed: 'variable', label: 'VSAT Satellite', status: 'active' } },
      { id: 'vessel-e2', source: 'node-vessel-4g', target: 'node-vessel-fw', data: { mediaType: 'wan', speed: 'variable', label: '4G LTE Backup', status: 'active' } },
      { id: 'vessel-e3', source: 'node-vessel-fw', target: 'node-vessel-bridge-sw', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [10, 99], status: 'active' } },
      { id: 'vessel-e4', source: 'node-vessel-fw', target: 'node-vessel-engine-sw', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [20, 99], status: 'active' } },
      { id: 'vessel-e5', source: 'node-vessel-fw', target: 'node-vessel-crew-sw', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [30, 99], status: 'active' } },
      { id: 'vessel-e6', source: 'node-vessel-fw', target: 'node-vessel-pax-sw', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [40, 99], status: 'active' } },
      { id: 'vessel-e7', source: 'node-vessel-bridge-sw', target: 'node-vessel-gmdss', data: { mediaType: 'copper', speed: '100M', vlanTag: 10, status: 'active' } },
      { id: 'vessel-e8', source: 'node-vessel-bridge-sw', target: 'node-vessel-nav-srv', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'vessel-e9', source: 'node-vessel-bridge-sw', target: 'node-vessel-ais', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'vessel-e10', source: 'node-vessel-bridge-sw', target: 'node-vessel-vdr', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'vessel-e11', source: 'node-vessel-engine-sw', target: 'node-vessel-engine-ctrl', data: { mediaType: 'fiber', speed: '1G', vlanTag: 20, status: 'active' } },
      { id: 'vessel-e12', source: 'node-vessel-pax-sw', target: 'node-vessel-pax-ap1', data: { mediaType: 'copper', speed: '1G', vlanTag: 40, poe: true, status: 'active' } },
      { id: 'vessel-e13', source: 'node-vessel-pax-sw', target: 'node-vessel-pax-ap2', data: { mediaType: 'copper', speed: '1G', vlanTag: 40, poe: true, status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.8 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'vessel-sim-1',
      name: 'Navigation Server can reach AIS Transponder',
      type: 'reachability',
      sourceNodeId: 'node-vessel-nav-srv',
      targetNodeId: 'node-vessel-ais',
      expectedResult: 'pass',
      description: 'Navigation server and AIS transponder on VLAN 10 communicate over the bridge network switch',
    },
    {
      id: 'vessel-sim-2',
      name: 'VDR can reach Bridge Switch',
      type: 'reachability',
      sourceNodeId: 'node-vessel-vdr',
      targetNodeId: 'node-vessel-bridge-sw',
      expectedResult: 'pass',
      description: 'The Voyage Data Recorder must have connectivity to the bridge network for data collection',
    },
    {
      id: 'vessel-sim-3',
      name: 'Passenger network is isolated from Bridge',
      type: 'isolation',
      sourceNodeId: 'node-vessel-pax-ap1',
      targetNodeId: 'node-vessel-bridge-sw',
      expectedResult: 'pass',
      description: 'Passenger WiFi devices on VLAN 40 must not be able to reach bridge navigation systems on VLAN 10',
    },
    {
      id: 'vessel-sim-4',
      name: 'Crew network is isolated from Bridge navigation',
      type: 'isolation',
      sourceNodeId: 'node-vessel-crew-sw',
      targetNodeId: 'node-vessel-nav-srv',
      expectedResult: 'pass',
      description: 'Crew network VLAN 30 must not be able to reach bridge navigation systems on VLAN 10',
    },
    {
      id: 'vessel-sim-5',
      name: 'Passenger can reach internet via VSAT',
      type: 'internet-access',
      sourceNodeId: 'node-vessel-pax-ap1',
      targetNodeId: 'node-vessel-vsat',
      expectedResult: 'pass',
      description: 'Passenger devices on VLAN 40 can reach internet through the VSAT gateway via the vessel firewall',
    },
    {
      id: 'vessel-sim-6',
      name: 'Bridge network is isolated from internet',
      type: 'isolation',
      sourceNodeId: 'node-vessel-nav-srv',
      targetNodeId: 'node-vessel-vsat',
      expectedResult: 'pass',
      description: 'Navigation and safety systems on VLAN 10 must not have internet access; only the COMMS VLAN 50 handles external connectivity',
    },
  ],
}
