import type { NetForgeTemplate } from '../../types/index.js'

export const oilGasScadaTemplate: NetForgeTemplate = {
  id: 'system-oil-gas-scada',
  slug: 'oil-gas-scada',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Oil and Gas SCADA Network',
    category: 'industrial',
    description: 'IEC 62443-compliant oil and gas SCADA network with Purdue Model zoning, separated Safety Instrumented System, remote RTU connectivity via cellular and satellite backup.',
    tags: ['scada', 'ot', 'industrial', 'iec62443', 'nist-csf', 'oil-gas'],
    difficulty: 'advanced',
    deviceCount: 16,
    thumbnail: '',
    notes: 'Zones: PROCESS 172.20.10.0/24, SAFETY 172.20.20.0/24 (SIS ONLY - isolated), OT-ENG 172.20.30.0/24, OT-DMZ 172.20.40.0/24. SIS must remain isolated from all other zones. Validation may warn about cellular and satellite paths.',
    validationExpected: 'warnings',
  },
  topology: {
    nodes: [
      {
        id: 'node-oilgas-internet',
        type: 'internet',
        position: { x: 800, y: 0 },
        data: { hostname: 'INTERNET', label: 'Internet', deviceType: 'internet' },
      },
      {
        id: 'node-oilgas-corp-router',
        type: 'router',
        position: { x: 800, y: 150 },
        data: {
          hostname: 'rtr-corporate',
          label: 'Corporate Router',
          deviceType: 'router',
          ipAddress: '172.20.40.1/24',
          subnet: '172.20.40.0/24',
          role: 'gateway',
        },
      },
      {
        id: 'node-oilgas-fw-dmz',
        type: 'firewall',
        position: { x: 800, y: 300 },
        data: {
          hostname: 'fw-ot-dmz',
          label: 'Firewall/DMZ',
          deviceType: 'firewall',
          ipAddress: '172.20.40.10/24',
          subnet: '172.20.40.0/24',
          role: 'ot-dmz-firewall',
        },
      },
      {
        id: 'node-oilgas-scada',
        type: 'server',
        position: { x: 400, y: 300 },
        data: {
          hostname: 'srv-scada-01',
          label: 'SCADA Server',
          deviceType: 'server',
          ipAddress: '172.20.10.10/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'scada',
        },
      },
      {
        id: 'node-oilgas-historian',
        type: 'server',
        position: { x: 600, y: 300 },
        data: {
          hostname: 'srv-historian',
          label: 'Historian Server',
          deviceType: 'server',
          ipAddress: '172.20.10.11/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'historian',
        },
      },
      {
        id: 'node-oilgas-hmi1',
        type: 'hmi',
        position: { x: 200, y: 300 },
        data: {
          hostname: 'hmi-process-01',
          label: 'HMI 1',
          deviceType: 'hmi',
          ipAddress: '172.20.10.20/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
        },
      },
      {
        id: 'node-oilgas-hmi2',
        type: 'hmi',
        position: { x: 200, y: 450 },
        data: {
          hostname: 'hmi-process-02',
          label: 'HMI 2',
          deviceType: 'hmi',
          ipAddress: '172.20.10.21/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
        },
      },
      {
        id: 'node-oilgas-ot-eng',
        type: 'workstation',
        position: { x: 1000, y: 300 },
        data: {
          hostname: 'ws-ot-engineer',
          label: 'Engineering Workstation',
          deviceType: 'workstation',
          ipAddress: '172.20.30.10/24',
          subnet: '172.20.30.0/24',
          vlanId: 30,
          role: 'ot-engineer',
        },
      },
      {
        id: 'node-oilgas-dcs1',
        type: 'plc',
        position: { x: 300, y: 500 },
        data: {
          hostname: 'dcs-ctrl-01',
          label: 'DCS Controller 1',
          deviceType: 'plc',
          ipAddress: '172.20.10.30/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'dcs',
        },
      },
      {
        id: 'node-oilgas-dcs2',
        type: 'plc',
        position: { x: 500, y: 500 },
        data: {
          hostname: 'dcs-ctrl-02',
          label: 'DCS Controller 2',
          deviceType: 'plc',
          ipAddress: '172.20.10.31/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'dcs',
        },
      },
      {
        id: 'node-oilgas-sis',
        type: 'plc',
        position: { x: 0, y: 300 },
        data: {
          hostname: 'sis-controller',
          label: 'SIS Controller',
          deviceType: 'plc',
          ipAddress: '172.20.20.10/24',
          subnet: '172.20.20.0/24',
          vlanId: 20,
          role: 'sis-controller',
          notes: 'Safety Instrumented System - must remain isolated from all other network zones',
        },
      },
      {
        id: 'node-oilgas-field-sw1',
        type: 'switch-l2',
        position: { x: 100, y: 650 },
        data: {
          hostname: 'sw-field-01',
          label: 'Field Switch 1',
          deviceType: 'switch-l2',
          ipAddress: '172.20.10.40/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'field-switch',
        },
      },
      {
        id: 'node-oilgas-field-sw2',
        type: 'switch-l2',
        position: { x: 300, y: 650 },
        data: {
          hostname: 'sw-field-02',
          label: 'Field Switch 2',
          deviceType: 'switch-l2',
          ipAddress: '172.20.10.41/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'field-switch',
        },
      },
      {
        id: 'node-oilgas-field-sw3',
        type: 'switch-l2',
        position: { x: 500, y: 650 },
        data: {
          hostname: 'sw-field-03',
          label: 'Field Switch 3',
          deviceType: 'switch-l2',
          ipAddress: '172.20.10.42/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'field-switch',
        },
      },
      {
        id: 'node-oilgas-field-sw4',
        type: 'switch-l2',
        position: { x: 700, y: 650 },
        data: {
          hostname: 'sw-field-04',
          label: 'Field Switch 4',
          deviceType: 'switch-l2',
          ipAddress: '172.20.10.43/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'field-switch',
        },
      },
      {
        id: 'node-oilgas-rtu1',
        type: 'plc',
        position: { x: 100, y: 800 },
        data: {
          hostname: 'rtu-remote-01',
          label: 'RTU 1',
          deviceType: 'plc',
          ipAddress: '172.20.10.50/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'rtu',
        },
      },
      {
        id: 'node-oilgas-rtu2',
        type: 'plc',
        position: { x: 300, y: 800 },
        data: {
          hostname: 'rtu-remote-02',
          label: 'RTU 2',
          deviceType: 'plc',
          ipAddress: '172.20.10.51/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'rtu',
        },
      },
      {
        id: 'node-oilgas-rtu3',
        type: 'plc',
        position: { x: 500, y: 800 },
        data: {
          hostname: 'rtu-remote-03',
          label: 'RTU 3',
          deviceType: 'plc',
          ipAddress: '172.20.10.52/24',
          subnet: '172.20.10.0/24',
          vlanId: 10,
          role: 'rtu',
        },
      },
      {
        id: 'node-oilgas-cellular-gw',
        type: 'router',
        position: { x: 300, y: 150 },
        data: {
          hostname: 'rtr-cellular-gw',
          label: 'Cellular Gateway',
          deviceType: 'router',
          ipAddress: '172.20.40.20/24',
          subnet: '172.20.40.0/24',
          role: 'cellular-gateway',
        },
      },
      {
        id: 'node-oilgas-sat-gw',
        type: 'router',
        position: { x: 600, y: 150 },
        data: {
          hostname: 'rtr-satellite-gw',
          label: 'Satellite Gateway',
          deviceType: 'router',
          ipAddress: '172.20.40.21/24',
          subnet: '172.20.40.0/24',
          role: 'satellite-gateway',
        },
      },
    ],
    edges: [
      { id: 'oilgas-e1', source: 'node-oilgas-internet', target: 'node-oilgas-corp-router', data: { mediaType: 'wan', speed: 'variable', label: 'WAN', status: 'active' } },
      { id: 'oilgas-e2', source: 'node-oilgas-corp-router', target: 'node-oilgas-fw-dmz', data: { mediaType: 'fiber', speed: '1G', status: 'active', label: 'OT-DMZ Boundary' } },
      { id: 'oilgas-e3', source: 'node-oilgas-fw-dmz', target: 'node-oilgas-scada', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e4', source: 'node-oilgas-fw-dmz', target: 'node-oilgas-historian', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e5', source: 'node-oilgas-fw-dmz', target: 'node-oilgas-ot-eng', data: { mediaType: 'fiber', speed: '1G', vlanTag: 30, status: 'active' } },
      { id: 'oilgas-e6', source: 'node-oilgas-scada', target: 'node-oilgas-hmi1', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e7', source: 'node-oilgas-scada', target: 'node-oilgas-hmi2', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e8', source: 'node-oilgas-scada', target: 'node-oilgas-dcs1', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, protocol: 'modbus-tcp', label: 'Modbus TCP', status: 'active' } },
      { id: 'oilgas-e9', source: 'node-oilgas-scada', target: 'node-oilgas-dcs2', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, protocol: 'modbus-tcp', label: 'Modbus TCP', status: 'active' } },
      { id: 'oilgas-e10', source: 'node-oilgas-sis', target: 'node-oilgas-field-sw1', data: { mediaType: 'fiber', speed: '1G', label: 'SAFETY SYSTEM - DO NOT MODIFY', status: 'active' } },
      { id: 'oilgas-e11', source: 'node-oilgas-dcs1', target: 'node-oilgas-field-sw1', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e12', source: 'node-oilgas-dcs1', target: 'node-oilgas-field-sw2', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e13', source: 'node-oilgas-dcs2', target: 'node-oilgas-field-sw3', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e14', source: 'node-oilgas-dcs2', target: 'node-oilgas-field-sw4', data: { mediaType: 'fiber', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'oilgas-e15', source: 'node-oilgas-cellular-gw', target: 'node-oilgas-rtu1', data: { mediaType: 'wireless', speed: 'variable', label: '4G LTE / Modbus RTU', status: 'active' } },
      { id: 'oilgas-e16', source: 'node-oilgas-cellular-gw', target: 'node-oilgas-rtu2', data: { mediaType: 'wireless', speed: 'variable', label: '4G LTE / Modbus RTU', status: 'active' } },
      { id: 'oilgas-e17', source: 'node-oilgas-cellular-gw', target: 'node-oilgas-rtu3', data: { mediaType: 'wireless', speed: 'variable', label: '4G LTE / Modbus RTU', status: 'active' } },
      { id: 'oilgas-e18', source: 'node-oilgas-sat-gw', target: 'node-oilgas-internet', data: { mediaType: 'wan', speed: 'variable', label: 'VSAT Backup', status: 'active' } },
      { id: 'oilgas-e19', source: 'node-oilgas-fw-dmz', target: 'node-oilgas-cellular-gw', data: { mediaType: 'fiber', speed: '1G', status: 'active' } },
      { id: 'oilgas-e20', source: 'node-oilgas-fw-dmz', target: 'node-oilgas-sat-gw', data: { mediaType: 'fiber', speed: '1G', status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.7 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'oilgas-sim-1',
      name: 'SCADA Server can reach DCS Controller',
      type: 'reachability',
      sourceNodeId: 'node-oilgas-scada',
      targetNodeId: 'node-oilgas-dcs1',
      expectedResult: 'pass',
      description: 'SCADA server on VLAN 10 can communicate with DCS controllers via Modbus TCP in the process zone',
    },
    {
      id: 'oilgas-sim-2',
      name: 'SIS is isolated from process zone',
      type: 'isolation',
      sourceNodeId: 'node-oilgas-sis',
      targetNodeId: 'node-oilgas-scada',
      expectedResult: 'pass',
      description: 'The Safety Instrumented System must remain isolated from the process zone SCADA network per IEC 62443 SIL requirements',
    },
    {
      id: 'oilgas-sim-3',
      name: 'SIS is isolated from corporate network',
      type: 'isolation',
      sourceNodeId: 'node-oilgas-sis',
      targetNodeId: 'node-oilgas-corp-router',
      expectedResult: 'pass',
      description: 'The SIS must have zero connectivity to corporate or internet networks at all times',
    },
    {
      id: 'oilgas-sim-4',
      name: 'RTU reaches SCADA via cellular gateway',
      type: 'reachability',
      sourceNodeId: 'node-oilgas-rtu1',
      targetNodeId: 'node-oilgas-scada',
      expectedResult: 'pass',
      description: 'Remote RTUs communicate with the SCADA server through the cellular gateway and DMZ firewall',
    },
    {
      id: 'oilgas-sim-5',
      name: 'OT Engineer can reach DCS Controller',
      type: 'reachability',
      sourceNodeId: 'node-oilgas-ot-eng',
      targetNodeId: 'node-oilgas-dcs1',
      expectedResult: 'pass',
      description: 'OT engineers on the engineering VLAN 30 can access DCS controllers for programming and maintenance',
    },
    {
      id: 'oilgas-sim-6',
      name: 'Corporate network isolated from DCS',
      type: 'isolation',
      sourceNodeId: 'node-oilgas-corp-router',
      targetNodeId: 'node-oilgas-dcs1',
      expectedResult: 'pass',
      description: 'Corporate network traffic must not be able to reach process zone DCS controllers; the DMZ firewall enforces this boundary',
    },
  ],
}
