import type { NetForgeTemplate } from '../../types/index.js'

export const zeroTrustNetworkTemplate: NetForgeTemplate = {
  id: 'system-zero-trust-network',
  slug: 'zero-trust-network',
  version: '1.0.0',
  isSystem: true,
  orgId: null,
  createdBy: null,
  meta: {
    name: 'Zero Trust Network Architecture',
    category: 'specialty',
    description: 'Zero Trust Network Architecture enforcing per-session identity verification with microsegmentation. No implicit trust for any device regardless of network location.',
    tags: ['zero-trust', 'ztna', 'microsegmentation', 'nist-csf', 'cmmc'],
    difficulty: 'advanced',
    deviceCount: 15,
    thumbnail: '',
    notes: 'VLANs: 10=ENDPOINTS, 20=APP-TIER, 30=DATA-TIER, 40=IDENTITY, 50=REMOTE, 99=MGMT. All access requires identity verification via IdP. Microsegmentation gateways enforce east-west traffic policies.',
    validationExpected: 'pass',
  },
  topology: {
    nodes: [
      // Internet
      {
        id: 'node-ztna-internet',
        type: 'internet',
        position: { x: 800, y: 0 },
        data: { hostname: 'INTERNET', label: 'Internet', deviceType: 'internet' },
      },
      // Remote VPN Users
      {
        id: 'node-ztna-remote1',
        type: 'workstation',
        position: { x: 600, y: 0 },
        data: {
          hostname: 'remote-user-01',
          label: 'Remote User 1',
          deviceType: 'workstation',
          ipAddress: '10.100.50.11/24',
          subnet: '10.100.50.0/24',
          vlanId: 50,
          role: 'remote-user',
          notes: 'Remote VPN user on VLAN 50',
        },
      },
      {
        id: 'node-ztna-remote2',
        type: 'workstation',
        position: { x: 1000, y: 0 },
        data: {
          hostname: 'remote-user-02',
          label: 'Remote User 2',
          deviceType: 'workstation',
          ipAddress: '10.100.50.12/24',
          subnet: '10.100.50.0/24',
          vlanId: 50,
          role: 'remote-user',
          notes: 'Remote VPN user on VLAN 50',
        },
      },
      // Firewall
      {
        id: 'node-ztna-fw',
        type: 'firewall',
        position: { x: 800, y: 150 },
        data: {
          hostname: 'fw-ztna-edge',
          label: 'Edge Firewall',
          deviceType: 'firewall',
          ipAddress: '10.100.99.1/24',
          subnet: '10.100.99.0/24',
          vlanId: 99,
          role: 'gateway',
        },
      },
      // Zero Trust Controller
      {
        id: 'node-ztna-controller',
        type: 'server',
        position: { x: 400, y: 300 },
        data: {
          hostname: 'ztna-controller',
          label: 'Zero Trust Controller',
          deviceType: 'server',
          ipAddress: '10.100.99.10/24',
          subnet: '10.100.99.0/24',
          vlanId: 99,
          role: 'ztna-controller',
          notes: 'Evaluates per-session access requests',
        },
      },
      // Identity Provider
      {
        id: 'node-ztna-idp',
        type: 'server',
        position: { x: 400, y: 150 },
        data: {
          hostname: 'idp-01',
          label: 'Identity Provider',
          deviceType: 'server',
          ipAddress: '10.100.40.10/24',
          subnet: '10.100.40.0/24',
          vlanId: 40,
          role: 'identity-provider',
          notes: 'SAML/OIDC identity provider for ZTNA authentication',
        },
      },
      // Core Switch
      {
        id: 'node-ztna-core-sw',
        type: 'switch-l3',
        position: { x: 800, y: 300 },
        data: {
          hostname: 'sw-core-ztna',
          label: 'Core Switch',
          deviceType: 'switch-l3',
          ipAddress: '10.100.99.2/24',
          subnet: '10.100.99.0/24',
          interVlanRouting: true,
          vlanTrunkPorts: [10, 20, 30, 40, 50, 99],
        },
      },
      // Microsegmentation Gateways
      {
        id: 'node-ztna-mseg1',
        type: 'firewall-edge',
        position: { x: 400, y: 500 },
        data: {
          hostname: 'mseg-gw-01',
          label: 'Microseg Gateway A',
          deviceType: 'firewall-edge',
          ipAddress: '10.100.99.20/24',
          subnet: '10.100.99.0/24',
          vlanId: 99,
          role: 'microseg-gateway',
          notes: 'Enforces east-west microsegmentation policy for endpoints and app tier',
        },
      },
      {
        id: 'node-ztna-mseg2',
        type: 'firewall-edge',
        position: { x: 1200, y: 500 },
        data: {
          hostname: 'mseg-gw-02',
          label: 'Microseg Gateway B',
          deviceType: 'firewall-edge',
          ipAddress: '10.100.99.21/24',
          subnet: '10.100.99.0/24',
          vlanId: 99,
          role: 'microseg-gateway',
          notes: 'Enforces east-west microsegmentation policy for data tier',
        },
      },
      // Access Switches
      {
        id: 'node-ztna-acc-sw1',
        type: 'switch-l2',
        position: { x: 300, y: 700 },
        data: {
          hostname: 'sw-acc-ztna-01',
          label: 'Access Switch 1',
          deviceType: 'switch-l2',
          ipAddress: '10.100.99.11/24',
          subnet: '10.100.99.0/24',
          vlanTrunkPorts: [10, 40, 99],
        },
      },
      {
        id: 'node-ztna-acc-sw2',
        type: 'switch-l2',
        position: { x: 700, y: 700 },
        data: {
          hostname: 'sw-acc-ztna-02',
          label: 'Access Switch 2',
          deviceType: 'switch-l2',
          ipAddress: '10.100.99.12/24',
          subnet: '10.100.99.0/24',
          vlanTrunkPorts: [10, 99],
        },
      },
      // Workstations (VLAN 10)
      {
        id: 'node-ztna-ws1',
        type: 'workstation',
        position: { x: 100, y: 900 },
        data: {
          hostname: 'ws-ztna-01',
          label: 'Workstation 1',
          deviceType: 'workstation',
          ipAddress: '10.100.10.11/24',
          subnet: '10.100.10.0/24',
          defaultGateway: '10.100.10.1',
          vlanId: 10,
        },
      },
      {
        id: 'node-ztna-ws2',
        type: 'workstation',
        position: { x: 300, y: 900 },
        data: {
          hostname: 'ws-ztna-02',
          label: 'Workstation 2',
          deviceType: 'workstation',
          ipAddress: '10.100.10.12/24',
          subnet: '10.100.10.0/24',
          defaultGateway: '10.100.10.1',
          vlanId: 10,
        },
      },
      {
        id: 'node-ztna-ws3',
        type: 'workstation',
        position: { x: 500, y: 900 },
        data: {
          hostname: 'ws-ztna-03',
          label: 'Workstation 3',
          deviceType: 'workstation',
          ipAddress: '10.100.10.13/24',
          subnet: '10.100.10.0/24',
          defaultGateway: '10.100.10.1',
          vlanId: 10,
        },
      },
      {
        id: 'node-ztna-ws4',
        type: 'workstation',
        position: { x: 700, y: 900 },
        data: {
          hostname: 'ws-ztna-04',
          label: 'Workstation 4',
          deviceType: 'workstation',
          ipAddress: '10.100.10.14/24',
          subnet: '10.100.10.0/24',
          defaultGateway: '10.100.10.1',
          vlanId: 10,
        },
      },
      // App Servers (VLAN 20)
      {
        id: 'node-ztna-app1',
        type: 'server',
        position: { x: 1000, y: 700 },
        data: {
          hostname: 'app-srv-01',
          label: 'App Server 1',
          deviceType: 'server',
          ipAddress: '10.100.20.10/24',
          subnet: '10.100.20.0/24',
          defaultGateway: '10.100.20.1',
          vlanId: 20,
          role: 'app-server',
        },
      },
      {
        id: 'node-ztna-app2',
        type: 'server',
        position: { x: 1200, y: 700 },
        data: {
          hostname: 'app-srv-02',
          label: 'App Server 2',
          deviceType: 'server',
          ipAddress: '10.100.20.11/24',
          subnet: '10.100.20.0/24',
          defaultGateway: '10.100.20.1',
          vlanId: 20,
          role: 'app-server',
        },
      },
      // DB Server (VLAN 30)
      {
        id: 'node-ztna-db',
        type: 'server',
        position: { x: 1400, y: 700 },
        data: {
          hostname: 'db-srv-01',
          label: 'DB Server',
          deviceType: 'server',
          ipAddress: '10.100.30.10/24',
          subnet: '10.100.30.0/24',
          defaultGateway: '10.100.30.1',
          vlanId: 30,
          role: 'db-server',
        },
      },
    ],
    edges: [
      { id: 'ztna-e1', source: 'node-ztna-remote1', target: 'node-ztna-fw', data: { mediaType: 'vpn', speed: 'variable', protocol: 'ssl-vpn', label: 'SSL VPN Tunnel', status: 'active' } },
      { id: 'ztna-e2', source: 'node-ztna-remote2', target: 'node-ztna-fw', data: { mediaType: 'vpn', speed: 'variable', protocol: 'ssl-vpn', label: 'SSL VPN Tunnel', status: 'active' } },
      { id: 'ztna-e3', source: 'node-ztna-internet', target: 'node-ztna-fw', data: { mediaType: 'wan', speed: 'variable', label: 'WAN', status: 'active' } },
      { id: 'ztna-e4', source: 'node-ztna-fw', target: 'node-ztna-core-sw', data: { mediaType: 'fiber', speed: '10G', trunkVlans: [10, 20, 30, 40, 50, 99], uplink: true, status: 'active' } },
      { id: 'ztna-e5', source: 'node-ztna-core-sw', target: 'node-ztna-idp', data: { mediaType: 'fiber', speed: '1G', vlanTag: 40, label: 'Identity VLAN', status: 'active' } },
      { id: 'ztna-e6', source: 'node-ztna-core-sw', target: 'node-ztna-controller', data: { mediaType: 'fiber', speed: '1G', vlanTag: 99, label: 'ZTNA Control Plane', status: 'active' } },
      { id: 'ztna-e7', source: 'node-ztna-core-sw', target: 'node-ztna-mseg1', data: { mediaType: 'fiber', speed: '10G', trunkVlans: [10, 20, 99], uplink: true, status: 'active' } },
      { id: 'ztna-e8', source: 'node-ztna-core-sw', target: 'node-ztna-mseg2', data: { mediaType: 'fiber', speed: '10G', trunkVlans: [20, 30, 99], uplink: true, status: 'active' } },
      { id: 'ztna-e9', source: 'node-ztna-mseg1', target: 'node-ztna-acc-sw1', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [10, 99], status: 'active' } },
      { id: 'ztna-e10', source: 'node-ztna-mseg1', target: 'node-ztna-acc-sw2', data: { mediaType: 'fiber', speed: '1G', trunkVlans: [10, 99], status: 'active' } },
      { id: 'ztna-e11', source: 'node-ztna-acc-sw1', target: 'node-ztna-ws1', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'ztna-e12', source: 'node-ztna-acc-sw1', target: 'node-ztna-ws2', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'ztna-e13', source: 'node-ztna-acc-sw2', target: 'node-ztna-ws3', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'ztna-e14', source: 'node-ztna-acc-sw2', target: 'node-ztna-ws4', data: { mediaType: 'copper', speed: '1G', vlanTag: 10, status: 'active' } },
      { id: 'ztna-e15', source: 'node-ztna-mseg2', target: 'node-ztna-app1', data: { mediaType: 'fiber', speed: '10G', vlanTag: 20, status: 'active' } },
      { id: 'ztna-e16', source: 'node-ztna-mseg2', target: 'node-ztna-app2', data: { mediaType: 'fiber', speed: '10G', vlanTag: 20, status: 'active' } },
      { id: 'ztna-e17', source: 'node-ztna-mseg2', target: 'node-ztna-db', data: { mediaType: 'fiber', speed: '10G', vlanTag: 30, label: 'Data Tier - Restricted', status: 'active' } },
    ],
    viewport: { x: 0, y: 0, zoom: 0.75 },
    metadata: { gridEnabled: true, snapToGrid: true, theme: 'default' },
  },
  simTestSuite: [
    {
      id: 'ztna-sim-1',
      name: 'Workstation can reach App Server via ZTNA gateway',
      type: 'reachability',
      sourceNodeId: 'node-ztna-ws1',
      targetNodeId: 'node-ztna-app1',
      expectedResult: 'pass',
      description: 'Authenticated workstation on VLAN 10 can reach app server on VLAN 20 through microsegmentation gateway after identity verification',
    },
    {
      id: 'ztna-sim-2',
      name: 'Workstation is isolated from DB Server',
      type: 'isolation',
      sourceNodeId: 'node-ztna-ws1',
      targetNodeId: 'node-ztna-db',
      expectedResult: 'pass',
      description: 'Workstations on VLAN 10 must not have direct access to the DB server on VLAN 30 - gateway enforces data tier isolation',
    },
    {
      id: 'ztna-sim-3',
      name: 'Unauthenticated path to App Server blocked',
      type: 'isolation',
      sourceNodeId: 'node-ztna-internet',
      targetNodeId: 'node-ztna-app1',
      expectedResult: 'pass',
      description: 'Internet traffic cannot directly reach app servers - all access must pass through ZTNA controller and IdP verification',
    },
    {
      id: 'ztna-sim-4',
      name: 'App Server can reach DB Server via gateway',
      type: 'reachability',
      sourceNodeId: 'node-ztna-app1',
      targetNodeId: 'node-ztna-db',
      expectedResult: 'pass',
      description: 'App servers on VLAN 20 can reach the DB server on VLAN 30 through microsegmentation gateway B after policy evaluation',
    },
    {
      id: 'ztna-sim-5',
      name: 'Remote user can access internet via firewall',
      type: 'internet-access',
      sourceNodeId: 'node-ztna-remote1',
      targetNodeId: 'node-ztna-internet',
      expectedResult: 'pass',
      description: 'Remote VPN users on VLAN 50 can access internet through the edge firewall after authentication',
    },
  ],
}
