import type { TopologySnapshot, ValidationResult, SimulationResult, SimulationTest } from '@gridhive/shared'
import { PROTOCOL_LABELS, PROTOCOL_DESCRIPTIONS } from '@gridhive/shared'

export interface PDFOptions {
  includeValidation: boolean
  includeSimulation: boolean
  includeSubnet: boolean
  paperSize: 'Letter' | 'A4'
}

interface ReportContext {
  projectName: string
  orgName: string
  userName: string
  topology: TopologySnapshot
  validationResults: ValidationResult[]
  simulationResults: SimulationResult[]
  simulationTests: SimulationTest[]
  lastValidatedAt: Date | null
  lastSimulatedAt: Date | null
  canvasImageBase64?: string
}

const COLORS = {
  primary: '#1e40af',
  headerBg: '#1e293b',
  headerText: '#f8fafc',
  bodyText: '#1e293b',
  subtext: '#64748b',
  errorRed: '#dc2626',
  warningAmber: '#d97706',
  infoBlue: '#2563eb',
  successGreen: '#16a34a',
  rowAlt: '#f8fafc',
  rowError: '#fef2f2',
  rowWarning: '#fffbeb',
  border: '#e2e8f0',
}

function formatDate(date: Date | null): string {
  if (!date) return 'Not run'
  return new Intl.DateTimeFormat('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  }).format(date)
}

function buildCoverPage(ctx: ReportContext) {
  return [
    {
      columns: [
        {
          text: 'GRIDHIVE',
          style: 'logo',
          width: '*',
        },
      ],
      margin: [0, 0, 0, 20],
    },
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 2, lineColor: COLORS.primary }] },
    { text: '', margin: [0, 20] },
    {
      text: `${ctx.projectName}`,
      style: 'coverTitle',
    },
    {
      text: 'Network Documentation Report',
      style: 'coverSubtitle',
    },
    { text: '', margin: [0, 30] },
    {
      table: {
        widths: [120, '*'],
        body: [
          [
            { text: 'Generated By', style: 'metaLabel' },
            { text: ctx.userName, style: 'metaValue' },
          ],
          [
            { text: 'Organization', style: 'metaLabel' },
            { text: ctx.orgName, style: 'metaValue' },
          ],
          [
            { text: 'Date Generated', style: 'metaLabel' },
            { text: formatDate(new Date()), style: 'metaValue' },
          ],
          [
            { text: 'Total Devices', style: 'metaLabel' },
            { text: ctx.topology.nodes.length.toString(), style: 'metaValue' },
          ],
          [
            { text: 'Total Connections', style: 'metaLabel' },
            { text: ctx.topology.edges.length.toString(), style: 'metaValue' },
          ],
        ],
      },
      layout: 'noBorders',
      margin: [0, 0, 0, 40],
    },
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: COLORS.border }] },
  ]
}

function buildNetworkOverview(ctx: ReportContext) {
  const { topology, validationResults, lastValidatedAt } = ctx

  const vlans = [...new Set(topology.nodes.flatMap(n => {
    const vlans = []
    if (n.data.vlanId) vlans.push(`VLAN ${n.data.vlanId}`)
    return vlans
  }))].join(', ') || 'None defined'

  const subnets = [...new Set(topology.nodes
    .filter(n => n.data.subnet)
    .map(n => n.data.subnet!))].join(', ') || 'None defined'

  const protocols = [...new Set(topology.edges.flatMap(e => {
    const p = e.data.protocols || []
    return p.map(proto => PROTOCOL_LABELS[proto] || proto)
  }))].join(', ') || 'None'

  const errors = validationResults.filter(r => r.severity === 'error').length
  const warnings = validationResults.filter(r => r.severity === 'warning').length
  const validationStatus = lastValidatedAt
    ? errors > 0 ? `ERRORS (${errors} errors, ${warnings} warnings)`
    : warnings > 0 ? `WARNINGS (${warnings} warnings)`
    : 'CLEAN'
    : 'Not run'

  const content: object[] = [
    { text: 'Network Overview', style: 'sectionHeader', pageBreak: 'before' },
  ]

  if (ctx.canvasImageBase64) {
    content.push({
      image: ctx.canvasImageBase64,
      width: 515,
      margin: [0, 0, 0, 16],
    })
  }

  content.push({
    table: {
      widths: [150, '*'],
      body: [
        [{ text: 'Total Devices', style: 'tableHeader' }, { text: topology.nodes.length.toString(), style: 'tableCell' }],
        [{ text: 'Total Connections', style: 'tableHeader' }, { text: topology.edges.length.toString(), style: 'tableCell' }],
        [{ text: 'VLANs Defined', style: 'tableHeader' }, { text: vlans, style: 'tableCell' }],
        [{ text: 'Subnets in Use', style: 'tableHeader' }, { text: subnets, style: 'tableCell' }],
        [{ text: 'Protocols in Use', style: 'tableHeader' }, { text: protocols, style: 'tableCell' }],
        [{ text: 'Validation Status', style: 'tableHeader' }, {
          text: validationStatus,
          style: 'tableCell',
          color: errors > 0 ? COLORS.errorRed : warnings > 0 ? COLORS.warningAmber : COLORS.successGreen,
        }],
        [{ text: 'Last Validated', style: 'tableHeader' }, { text: formatDate(lastValidatedAt), style: 'tableCell' }],
      ],
    },
    layout: {
      hLineWidth: () => 0.5,
      vLineWidth: () => 0,
      hLineColor: () => COLORS.border,
      fillColor: (i: number) => i % 2 === 0 ? COLORS.rowAlt : null,
    },
  })

  return content
}

function buildDeviceInventory(ctx: ReportContext, validationResults: ValidationResult[]) {
  const errorNodeIds = new Set(validationResults.filter(r => r.severity === 'error').flatMap(r => r.affectedNodeIds))
  const warningNodeIds = new Set(validationResults.filter(r => r.severity === 'warning').flatMap(r => r.affectedNodeIds))

  const headers = ['Hostname', 'Type', 'IP Address', 'Subnet', 'VLAN', 'Gateway', 'Role', 'Notes']
  const rows = ctx.topology.nodes.map(node => {
    const isError = errorNodeIds.has(node.id)
    const isWarning = warningNodeIds.has(node.id)
    const fill = isError ? COLORS.rowError : isWarning ? COLORS.rowWarning : null

    return headers.map((_, i) => {
      const values = [
        node.data.hostname || '',
        node.data.deviceType,
        node.data.ipAddress || '',
        node.data.subnet || '',
        node.data.vlanId?.toString() || '',
        node.data.defaultGateway || '',
        node.data.role || '',
        node.data.notes || '',
      ]
      return {
        text: values[i],
        style: 'tableCell',
        fillColor: fill,
      }
    })
  })

  return [
    { text: 'Device Inventory', style: 'sectionHeader', pageBreak: 'before' },
    {
      table: {
        headerRows: 1,
        widths: [80, 65, 75, 75, 35, 70, 50, '*'],
        body: [
          headers.map(h => ({ text: h, style: 'columnHeader' })),
          ...rows,
        ],
      },
      layout: {
        hLineWidth: () => 0.5,
        vLineWidth: (i: number) => i === 0 || i === headers.length ? 0.5 : 0,
        hLineColor: () => COLORS.border,
        vLineColor: () => COLORS.border,
        fillColor: (row: number) => row === 0 ? COLORS.headerBg : null,
      },
    },
  ]
}

function buildConnectionInventory(ctx: ReportContext) {
  const headers = ['Source', 'Destination', 'Media', 'Speed', 'VLAN/Trunk', 'Protocols', 'Notes']
  const rows = ctx.topology.edges.map(edge => {
    const source = ctx.topology.nodes.find(n => n.id === edge.source)
    const target = ctx.topology.nodes.find(n => n.id === edge.target)
    const protocols = (edge.data.protocols || []).map(p => PROTOCOL_LABELS[p] || p).join(', ') || ''
    const vlanInfo = edge.data.vlanTag
      ? `VLAN ${edge.data.vlanTag}`
      : edge.data.trunkVlans?.length
      ? `Trunk: ${edge.data.trunkVlans.join(',')}`
      : ''

    return [
      { text: source?.data.hostname || edge.source, style: 'tableCell' },
      { text: target?.data.hostname || edge.target, style: 'tableCell' },
      { text: edge.data.mediaType || 'copper', style: 'tableCell' },
      { text: edge.data.speed || '1G', style: 'tableCell' },
      { text: vlanInfo, style: 'tableCell' },
      { text: protocols, style: 'tableCell' },
      { text: edge.data.notes || '', style: 'tableCell' },
    ]
  })

  return [
    { text: 'Connection Inventory', style: 'sectionHeader', pageBreak: 'before' },
    {
      table: {
        headerRows: 1,
        widths: [80, 80, 45, 40, 65, 70, '*'],
        body: [
          headers.map(h => ({ text: h, style: 'columnHeader' })),
          ...rows,
        ],
      },
      layout: {
        hLineWidth: () => 0.5,
        vLineWidth: (i: number) => i === 0 || i === headers.length ? 0.5 : 0,
        hLineColor: () => COLORS.border,
        vLineColor: () => COLORS.border,
        fillColor: (row: number) => row === 0 ? COLORS.headerBg : row % 2 === 0 ? COLORS.rowAlt : null,
      },
    },
  ]
}

function buildProtocolReference(ctx: ReportContext) {
  const allProtocols = [...new Set(ctx.topology.edges.flatMap(e => e.data.protocols || []))]

  if (allProtocols.length === 0) {
    return [
      { text: 'Protocols and Services', style: 'sectionHeader', pageBreak: 'before' },
      { text: 'No protocols assigned to any connection in this topology.', style: 'bodyText', margin: [0, 8] },
    ]
  }

  const rows = allProtocols.map(protocol => {
    const usedOn = ctx.topology.edges
      .filter(e => (e.data.protocols || []).includes(protocol))
      .map(e => {
        const src = ctx.topology.nodes.find(n => n.id === e.source)
        const tgt = ctx.topology.nodes.find(n => n.id === e.target)
        return `${src?.data.hostname || 'Unknown'} → ${tgt?.data.hostname || 'Unknown'}`
      }).join(', ')

    return [
      { text: PROTOCOL_LABELS[protocol] || protocol, style: 'tableCell', bold: true },
      { text: usedOn, style: 'tableCell' },
      { text: PROTOCOL_DESCRIPTIONS[protocol] || '', style: 'tableCell' },
    ]
  })

  return [
    { text: 'Protocols and Services', style: 'sectionHeader', pageBreak: 'before' },
    {
      table: {
        headerRows: 1,
        widths: [80, 160, '*'],
        body: [
          [
            { text: 'Protocol', style: 'columnHeader' },
            { text: 'Used On', style: 'columnHeader' },
            { text: 'Description', style: 'columnHeader' },
          ],
          ...rows,
        ],
      },
      layout: {
        hLineWidth: () => 0.5,
        vLineWidth: (i: number) => i === 0 || i === 3 ? 0.5 : 0,
        hLineColor: () => COLORS.border,
        vLineColor: () => COLORS.border,
        fillColor: (row: number) => row === 0 ? COLORS.headerBg : row % 2 === 0 ? COLORS.rowAlt : null,
      },
    },
  ]
}

function buildValidationReport(ctx: ReportContext) {
  const { validationResults, lastValidatedAt } = ctx

  const content: object[] = [
    { text: 'Validation Results', style: 'sectionHeader', pageBreak: 'before' },
  ]

  if (!lastValidatedAt) {
    content.push({
      text: 'Validation not run. Load the project and run Validate before exporting for a complete report.',
      style: 'bodyText',
      margin: [0, 8],
    })
    return content
  }

  if (validationResults.length === 0) {
    content.push({
      text: `Validation passed with no errors or warnings at ${formatDate(lastValidatedAt)}.`,
      style: 'bodyText',
      color: COLORS.successGreen,
      margin: [0, 8],
    })
    return content
  }

  for (const severity of ['error', 'warning', 'info'] as const) {
    const items = validationResults.filter(r => r.severity === severity)
    if (items.length === 0) continue

    const sectionColor = severity === 'error' ? COLORS.errorRed : severity === 'warning' ? COLORS.warningAmber : COLORS.infoBlue
    const label = severity === 'error' ? 'Errors' : severity === 'warning' ? 'Warnings' : 'Info'

    content.push({ text: `${label} (${items.length})`, style: 'subSectionHeader', color: sectionColor, margin: [0, 12, 0, 4] })

    for (const result of items) {
      content.push({
        table: {
          widths: ['*'],
          body: [[{
            stack: [
              { text: `${result.code}: ${result.title}`, bold: true, fontSize: 9, color: sectionColor },
              { text: result.description, fontSize: 8, color: COLORS.bodyText, margin: [0, 2, 0, 0] },
              result.recommendation
                ? { text: `Recommendation: ${result.recommendation}`, fontSize: 8, color: COLORS.subtext, margin: [0, 2, 0, 0], italics: true }
                : { text: '' },
            ],
            margin: [6, 4],
          }]],
        },
        layout: {
          hLineWidth: (i: number) => i === 0 || i === 1 ? 0.5 : 0,
          vLineWidth: (i: number) => i === 0 || i === 1 ? 0.5 : 0,
          hLineColor: () => sectionColor,
          vLineColor: () => sectionColor,
        },
        margin: [0, 2, 0, 2],
      })
    }
  }

  return content
}

function buildSimulationReport(ctx: ReportContext) {
  const { simulationResults, simulationTests, lastSimulatedAt } = ctx

  const content: object[] = [
    { text: 'Simulation Test Results', style: 'sectionHeader', pageBreak: 'before' },
  ]

  if (!lastSimulatedAt || simulationResults.length === 0) {
    content.push({
      text: 'Simulation tests have not been run for this topology.',
      style: 'bodyText',
      margin: [0, 8],
    })
    return content
  }

  for (const result of simulationResults) {
    const test = simulationTests.find(t => t.id === result.testId)
    const testName = test?.name || result.testId
    const resultColor = result.passed ? COLORS.successGreen : COLORS.errorRed

    content.push({
      table: {
        widths: ['*'],
        body: [[{
          stack: [
            {
              columns: [
                { text: testName, bold: true, fontSize: 9, width: '*' },
                { text: result.passed ? 'PASS' : 'FAIL', color: resultColor, bold: true, fontSize: 9, width: 'auto' },
              ],
            },
            test?.type ? { text: `Type: ${test.type}`, fontSize: 8, color: COLORS.subtext, margin: [0, 2, 0, 0] } : { text: '' },
            result.path.length > 0
              ? {
                  text: `Path: ${result.path.map(h => h.nodeLabel).join(' → ')}`,
                  fontSize: 8,
                  color: COLORS.bodyText,
                  margin: [0, 3, 0, 0],
                }
              : { text: '' },
            result.blockReason
              ? {
                  text: `Blocked: ${result.blockReason}`,
                  fontSize: 8,
                  color: COLORS.errorRed,
                  margin: [0, 2, 0, 0],
                }
              : { text: '' },
          ],
          margin: [6, 4],
        }]],
      },
      layout: {
        hLineWidth: (i: number) => i === 0 || i === 1 ? 0.5 : 0,
        vLineWidth: (i: number) => i === 0 || i === 1 ? 0.5 : 0,
        hLineColor: () => resultColor,
        vLineColor: () => resultColor,
      },
      margin: [0, 2, 0, 4],
    })
  }

  return content
}

function buildSubnetReference(ctx: ReportContext) {
  const nodesBySubnet: Record<string, typeof ctx.topology.nodes> = {}

  for (const node of ctx.topology.nodes) {
    if (node.data.subnet) {
      if (!nodesBySubnet[node.data.subnet]) nodesBySubnet[node.data.subnet] = []
      nodesBySubnet[node.data.subnet].push(node)
    }
  }

  const content: object[] = [
    { text: 'IP Addressing Reference', style: 'sectionHeader', pageBreak: 'before' },
  ]

  if (Object.keys(nodesBySubnet).length === 0) {
    content.push({ text: 'No subnets defined in this topology.', style: 'bodyText', margin: [0, 8] })
    return content
  }

  for (const [subnet, nodes] of Object.entries(nodesBySubnet)) {
    const assigned = nodes.map(n => `${n.data.ipAddress || 'unassigned'} → ${n.data.hostname}`).join(', ')
    content.push({
      table: {
        widths: [120, '*'],
        body: [
          [{ text: 'Subnet', style: 'tableHeader' }, { text: subnet, style: 'tableCell', bold: true }],
          [{ text: 'Assigned Devices', style: 'tableHeader' }, { text: assigned, style: 'tableCell' }],
        ],
      },
      layout: {
        hLineWidth: () => 0.5,
        vLineWidth: () => 0,
        hLineColor: () => COLORS.border,
        fillColor: (i: number) => i % 2 === 0 ? COLORS.rowAlt : null,
      },
      margin: [0, 4, 0, 8],
    })
  }

  return content
}

export async function generatePDF(ctx: ReportContext, options: PDFOptions): Promise<void> {
  // Dynamic import to keep bundle lean
  const pdfmake = await import('pdfmake/build/pdfmake')
  const pdfFonts = await import('pdfmake/build/vfs_fonts')

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pdfMakeLib = (pdfmake.default || pdfmake) as any
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const vfsFonts = pdfFonts as any
  const vfsData = vfsFonts?.default?.pdfMake?.vfs || vfsFonts?.pdfMake?.vfs
  if (vfsData) {
    pdfMakeLib.vfs = vfsData
  }
  const pdfMake = pdfMakeLib

  const content: object[] = [
    ...buildCoverPage(ctx),
    ...buildNetworkOverview(ctx),
    ...buildDeviceInventory(ctx, options.includeValidation ? ctx.validationResults : []),
    ...buildConnectionInventory(ctx),
    ...buildProtocolReference(ctx),
  ]

  if (options.includeSubnet) {
    content.push(...buildSubnetReference(ctx))
  }

  if (options.includeValidation) {
    content.push(...buildValidationReport(ctx))
  }

  if (options.includeSimulation) {
    content.push(...buildSimulationReport(ctx))
  }

  const pageSize = options.paperSize === 'A4' ? 'A4' : 'LETTER'

  const docDefinition = {
    pageSize,
    pageMargins: [40, 60, 40, 50] as [number, number, number, number],
    content,
    styles: {
      logo: {
        fontSize: 22,
        bold: true,
        color: COLORS.primary,
        letterSpacing: 3,
      },
      coverTitle: {
        fontSize: 28,
        bold: true,
        color: COLORS.headerBg,
        margin: [0, 20, 0, 8],
      },
      coverSubtitle: {
        fontSize: 14,
        color: COLORS.subtext,
        margin: [0, 0, 0, 30],
      },
      metaLabel: {
        fontSize: 9,
        color: COLORS.subtext,
        bold: true,
        margin: [0, 4, 0, 4],
      },
      metaValue: {
        fontSize: 9,
        color: COLORS.bodyText,
        margin: [0, 4, 0, 4],
      },
      sectionHeader: {
        fontSize: 16,
        bold: true,
        color: COLORS.primary,
        margin: [0, 0, 0, 16],
      },
      subSectionHeader: {
        fontSize: 12,
        bold: true,
        margin: [0, 8, 0, 4],
      },
      columnHeader: {
        fontSize: 8,
        bold: true,
        color: COLORS.headerText,
        fillColor: COLORS.headerBg,
        margin: [4, 4, 4, 4],
      },
      tableHeader: {
        fontSize: 8,
        bold: true,
        color: COLORS.subtext,
        margin: [4, 4, 4, 4],
      },
      tableCell: {
        fontSize: 8,
        color: COLORS.bodyText,
        margin: [4, 3, 4, 3],
      },
      bodyText: {
        fontSize: 9,
        color: COLORS.bodyText,
        lineHeight: 1.4,
      },
    },
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: `Gridhive | ${ctx.orgName}`, fontSize: 8, color: '#64748b', alignment: 'left' },
        { text: ctx.projectName, fontSize: 8, color: '#64748b', alignment: 'center' },
        { text: `Page ${currentPage} of ${pageCount}`, fontSize: 8, color: '#64748b', alignment: 'right' },
      ],
      margin: [40, 10, 40, 0] as [number, number, number, number],
    }),
    defaultStyle: {
      font: 'Roboto',
      fontSize: 9,
    },
  }

  const now = new Date()
  const dateStr = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`
  const filename = `${ctx.projectName.replace(/[^a-zA-Z0-9]/g, '_')}_${dateStr}_Network_Report.pdf`

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pdfMake.createPdf(docDefinition as any).download(filename)
}
