import type { TopologySnapshot, DeviceNode, VendorDeviceProfile, ConfigExportResult } from '@gridhive/shared'

const INSTRUCTIONS =
  "Paste into the switch CLI in config context (Aruba AOS-S). " +
  "Syntax differs from Cisco: use 'vlan-access' (not 'switchport access vlan'), " +
  "'tagged vlan' (not 'switchport trunk allowed vlan'). " +
  "Run 'write memory' when done to save."

// ─── helpers ──────────────────────────────────────────────────────────────────

interface VlanInfo {
  id: number
  name: string
  ip?: string
  subnetMask?: string
}

interface PortInfo {
  portId: string
  description: string
  mode: 'access' | 'trunk'
  accessVlan?: number
  taggedVlans?: number[]
  untaggedVlan?: number
  isEdge: boolean
}

function subnetPrefixToMask(prefix: number): string {
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join('.')
}

function sanitizeName(name: string): string {
  return `"${name.replace(/"/g, '')}"`
}

function collectVlans(topology: TopologySnapshot, device: DeviceNode): VlanInfo[] {
  const vlanMap = new Map<number, VlanInfo>()

  const addVlan = (id: number, name?: string) => {
    if (!vlanMap.has(id)) vlanMap.set(id, { id, name: name || `VLAN${id}` })
  }

  if (device.data.vlanId) {
    vlanMap.set(device.data.vlanId, {
      id: device.data.vlanId,
      name: `VLAN${device.data.vlanId}`,
      ip: device.data.ipAddress,
      subnetMask: device.data.subnet
        ? subnetPrefixToMask(parseInt(device.data.subnet, 10))
        : undefined,
    })
  }

  if (Array.isArray(device.data.vlanTrunkPorts)) {
    for (const v of device.data.vlanTrunkPorts) addVlan(v)
  }

  if (device.data.portMappings) {
    for (const pm of device.data.portMappings) {
      if (pm.vlanId) addVlan(pm.vlanId)
      if (Array.isArray(pm.trunkVlans)) {
        for (const v of pm.trunkVlans) addVlan(v)
      }
    }
  }

  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    if (Array.isArray(edge.data.trunkVlans)) {
      for (const v of edge.data.trunkVlans) addVlan(v)
    }
    if (edge.data.vlanTag) addVlan(edge.data.vlanTag)
    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    if (neighbor?.data.vlanId) addVlan(neighbor.data.vlanId, neighbor.data.label)
  }

  return Array.from(vlanMap.values()).sort((a, b) => a.id - b.id)
}

function collectPorts(topology: TopologySnapshot, device: DeviceNode): PortInfo[] {
  const ports: PortInfo[] = []

  // From portMappings
  if (device.data.portMappings && device.data.portMappings.length > 0) {
    for (let i = 0; i < device.data.portMappings.length; i++) {
      const pm = device.data.portMappings[i]
      const isTrunk =
        pm.portType === 'trunk' ||
        pm.portType === 'uplink' ||
        (pm.trunkVlans && pm.trunkVlans.length > 0)
      const portId = String(i + 1)
      ports.push({
        portId,
        description: pm.portName || `port-${portId}`,
        mode: isTrunk ? 'trunk' : 'access',
        accessVlan: isTrunk ? undefined : (pm.vlanId || 1),
        taggedVlans: isTrunk ? (pm.trunkVlans || []) : undefined,
        untaggedVlan: isTrunk ? pm.vlanId : undefined,
        isEdge: pm.portType === 'access',
      })
    }
    return ports
  }

  // Fall back to edges
  let portIndex = 1
  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    const isTrunk =
      (edge.data.trunkVlans && (edge.data.trunkVlans as number[]).length > 0) ||
      edge.data.connectionType === 'trunk-8021q'
    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    ports.push({
      portId: String(portIndex),
      description: neighbor?.data.label || `connection-${portIndex}`,
      mode: isTrunk ? 'trunk' : 'access',
      accessVlan: isTrunk ? undefined : (edge.data.vlanTag || 1),
      taggedVlans: isTrunk ? (edge.data.trunkVlans as number[] | undefined) : undefined,
      untaggedVlan: edge.data.nativeVlan,
      isEdge: edge.data.connectionType === 'access-port',
    })
    portIndex++
  }

  return ports
}

// ─── config builder ───────────────────────────────────────────────────────────

function buildConfig(
  device: DeviceNode,
  vlans: VlanInfo[],
  ports: PortInfo[],
): string {
  const d = device.data
  const hostname = d.hostname || 'aruba-switch'
  const lines: string[] = [
    `; Aruba AOS-S Configuration — generated by Gridhive`,
    `; Device: ${hostname}`,
    `; Generated: ${new Date().toISOString()}`,
    '; Paste in config context. Run "write memory" to save.',
    ';',
    `hostname ${sanitizeName(hostname)}`,
    '',
  ]

  // VLAN declarations
  if (vlans.length > 0) {
    lines.push('; ── VLANs ────────────────────────────────────────────────────')
    for (const vlan of vlans) {
      lines.push(`vlan ${vlan.id}`)
      lines.push(`   name ${sanitizeName(vlan.name)}`)
    }
    lines.push('')
  }

  // VLAN IP interfaces (Layer 3)
  const isL3 = d.deviceType === 'switch-l3' || d.deviceType === 'router' || d.interVlanRouting
  if (isL3) {
    lines.push('; ── VLAN IP Interfaces ───────────────────────────────────────')
    for (const vlan of vlans) {
      lines.push(`interface vlan ${vlan.id}`)
      if (vlan.ip && vlan.subnetMask) {
        lines.push(`   ip address ${vlan.ip} ${vlan.subnetMask}`)
      } else {
        lines.push('   ! ip address <IP> <MASK>  <- configure manually')
      }
      lines.push('   no shutdown')
    }
    lines.push('')
  }

  // Physical interfaces
  if (ports.length > 0) {
    lines.push('; ── Interfaces ──────────────────────────────────────────────')
    for (const port of ports) {
      lines.push(`interface ${port.portId}`)
      lines.push(`   name ${sanitizeName(port.description)}`)
      if (port.mode === 'access') {
        lines.push(`   vlan-access ${port.accessVlan || 1}`)
        if (port.isEdge) {
          lines.push('   spanning-tree admin-edge-port')
        }
      } else {
        if (port.taggedVlans && port.taggedVlans.length > 0) {
          for (const v of port.taggedVlans) {
            lines.push(`   tagged vlan ${v}`)
          }
        }
        if (port.untaggedVlan) {
          lines.push(`   untagged vlan ${port.untaggedVlan}`)
        } else {
          lines.push('   untagged vlan 1')
        }
      }
    }
    lines.push('')
  }

  // Default gateway
  if (d.defaultGateway) {
    lines.push('; ── Routing ──────────────────────────────────────────────────')
    lines.push(`ip default-gateway ${d.defaultGateway}`)
    lines.push('')
  }

  // Management
  lines.push('; ── Management ──────────────────────────────────────────────')
  lines.push('ip ssh')
  lines.push('no telnet-server')

  return lines.join('\n')
}

// ─── public API ───────────────────────────────────────────────────────────────

export function generateAruba(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult {
  const d = device.data
  const hostname = d.hostname || 'aruba-switch'
  const warnings: string[] = []

  const vlans = collectVlans(topology, device)
  const ports = collectPorts(topology, device)

  if (vlans.length === 0) {
    warnings.push('No VLAN information found — VLAN section will be empty.')
  }
  if (ports.length === 0) {
    warnings.push('No port mapping or edge data found — interface config is empty.')
  }
  if (!d.ipAddress) {
    warnings.push('No IP address on device — VLAN interface IPs are not configured.')
  }

  const content = buildConfig(device, vlans, ports)

  return {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'aruba-cli',
    filename: `${hostname}-aoss-config.txt`,
    content,
    warnings,
    instructions: INSTRUCTIONS,
  }
}
