import type { TopologySnapshot, DeviceNode, VendorDeviceProfile, ConfigExportResult } from '@gridhive/shared'

const INSTRUCTIONS =
  "Paste vlan-config.txt first in configure terminal mode, then paste running-config.txt. Run 'copy running-config startup-config' when done."

// ─── helpers ──────────────────────────────────────────────────────────────────

interface VlanInfo {
  id: number
  name: string
  ipAddress?: string
  subnetMask?: string
}

interface PortInfo {
  portId: string
  description: string
  mode: 'access' | 'trunk'
  accessVlan?: number
  trunkVlans?: number[]
  nativeVlan?: number
  isUplink: boolean
}

function collectVlans(topology: TopologySnapshot, device: DeviceNode): VlanInfo[] {
  const vlanMap = new Map<number, VlanInfo>()

  const addVlan = (id: number, name?: string) => {
    if (!vlanMap.has(id)) {
      vlanMap.set(id, { id, name: name || sanitizeVlanName(id) })
    }
  }

  if (device.data.vlanId) addVlan(device.data.vlanId)
  if (Array.isArray(device.data.vlanTrunkPorts)) {
    for (const v of device.data.vlanTrunkPorts) addVlan(v)
  }

  if (device.data.portMappings) {
    for (const pm of device.data.portMappings) {
      if (pm.vlanId) addVlan(pm.vlanId)
      if (Array.isArray(pm.trunkVlans)) {
        for (const v of pm.trunkVlans) addVlan(v)
      }
    }
  }

  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    if (Array.isArray(edge.data.trunkVlans)) {
      for (const v of edge.data.trunkVlans) addVlan(v)
    }
    if (edge.data.vlanTag) addVlan(edge.data.vlanTag)

    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    if (neighbor?.data.vlanId) {
      addVlan(neighbor.data.vlanId, neighbor.data.label || undefined)
    }
  }

  // Attach IP to first (or primary) VLAN if device has an IP
  if (device.data.ipAddress && device.data.vlanId && vlanMap.has(device.data.vlanId)) {
    const entry = vlanMap.get(device.data.vlanId)!
    entry.ipAddress = device.data.ipAddress
    entry.subnetMask = subnetPrefixToMask(device.data.subnet ? parseInt(device.data.subnet, 10) : 24)
  }

  return Array.from(vlanMap.values()).sort((a, b) => a.id - b.id)
}

function collectPorts(topology: TopologySnapshot, device: DeviceNode): PortInfo[] {
  const ports: PortInfo[] = []
  let portIndex = 1

  // Build from portMappings if available
  if (device.data.portMappings && device.data.portMappings.length > 0) {
    for (const pm of device.data.portMappings) {
      const isUplink = pm.portType === 'uplink' || pm.portType === 'trunk'
      const isTrunk = pm.portType === 'trunk' || pm.portType === 'uplink' || (pm.trunkVlans && pm.trunkVlans.length > 0)
      ports.push({
        portId: `GigabitEthernet1/0/${portIndex}`,
        description: pm.portName || `port-${portIndex}`,
        mode: isTrunk ? 'trunk' : 'access',
        accessVlan: isTrunk ? undefined : (pm.vlanId || 1),
        trunkVlans: isTrunk ? (pm.trunkVlans || []) : undefined,
        nativeVlan: pm.vlanId,
        isUplink,
      })
      portIndex++
    }
    return ports
  }

  // Fall back to edges
  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue

    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    const isTrunk = (edge.data.trunkVlans && edge.data.trunkVlans.length > 0) ||
      edge.data.connectionType === 'trunk-8021q'

    const srcPort = edge.source === device.id ? edge.data.sourcePort : edge.data.targetPort
    const portId = srcPort || `GigabitEthernet1/0/${portIndex}`

    ports.push({
      portId,
      description: neighbor?.data.label || `connection-${portIndex}`,
      mode: isTrunk ? 'trunk' : 'access',
      accessVlan: isTrunk ? undefined : (edge.data.vlanTag || 1),
      trunkVlans: isTrunk ? (edge.data.trunkVlans as number[] | undefined) : undefined,
      nativeVlan: edge.data.nativeVlan,
      isUplink: edge.data.uplink === true,
    })
    portIndex++
  }

  return ports
}

function sanitizeVlanName(id: number): string {
  return `VLAN${id}`
}

function subnetPrefixToMask(prefix: number): string {
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join('.')
}

// ─── VLAN database config ─────────────────────────────────────────────────────

function buildVlanConfig(vlans: VlanInfo[]): string {
  const lines: string[] = [
    '! VLAN Database Configuration — generated by Gridhive',
    '! Paste in configure terminal mode.',
    '!',
    'vtp mode transparent',
    '!',
  ]

  for (const vlan of vlans) {
    lines.push(`vlan ${vlan.id}`)
    lines.push(` name ${vlan.name}`)
    lines.push('!')
  }

  return lines.join('\n')
}

// ─── Running config ───────────────────────────────────────────────────────────

function buildRunningConfig(
  device: DeviceNode,
  vlans: VlanInfo[],
  ports: PortInfo[],
): string {
  const d = device.data
  const hostname = d.hostname || 'SWITCH-01'
  const lines: string[] = [
    '! Running Configuration — generated by Gridhive',
    '! IOS-XE 17.x syntax. Paste in configure terminal mode.',
    '!',
    `hostname ${hostname}`,
    '!',
    'vtp mode transparent',
    '!',
  ]

  // VLAN declarations
  for (const vlan of vlans) {
    lines.push(`vlan ${vlan.id}`)
    lines.push(` name ${vlan.name}`)
    lines.push('!')
  }

  // SVI interfaces (Layer 3 only)
  const isL3 = d.deviceType === 'switch-l3' || d.deviceType === 'router' || d.interVlanRouting
  if (isL3) {
    for (const vlan of vlans) {
      lines.push(`interface Vlan${vlan.id}`)
      lines.push(` description ${vlan.name}`)
      if (vlan.ipAddress && vlan.subnetMask) {
        lines.push(` ip address ${vlan.ipAddress} ${vlan.subnetMask}`)
      } else {
        lines.push(' ! ip address <IP> <MASK>  ← configure manually')
      }
      lines.push(' no shutdown')
      lines.push('!')
    }
  }

  // Physical port interfaces
  for (const port of ports) {
    lines.push(`interface ${port.portId}`)
    lines.push(` description ${port.description}`)
    if (port.mode === 'trunk') {
      lines.push(' switchport mode trunk')
      if (port.trunkVlans && port.trunkVlans.length > 0) {
        lines.push(` switchport trunk allowed vlan ${port.trunkVlans.join(',')}`)
      }
      if (port.nativeVlan) {
        lines.push(` switchport trunk native vlan ${port.nativeVlan}`)
      }
    } else {
      lines.push(' switchport mode access')
      lines.push(` switchport access vlan ${port.accessVlan || 1}`)
      if (!port.isUplink) {
        lines.push(' spanning-tree portfast')
      }
    }
    lines.push(' no shutdown')
    lines.push('!')
  }

  // Default gateway (L3 switches / routers)
  if (d.defaultGateway) {
    lines.push(`ip default-gateway ${d.defaultGateway}`)
    lines.push('!')
  }

  // Management VTY
  lines.push('line vty 0 15')
  lines.push(' transport input ssh')
  lines.push(' login local')
  lines.push('!')
  lines.push('end')

  return lines.join('\n')
}

// ─── public API ───────────────────────────────────────────────────────────────

/**
 * Generates two Cisco IOS config files: vlan-config.txt and running-config.txt.
 */
export function generateCiscoIOSConfig(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult[] {
  const d = device.data
  const hostname = d.hostname || 'SWITCH-01'
  const warnings: string[] = []
  const vlans = collectVlans(topology, device)
  const ports = collectPorts(topology, device)

  if (vlans.length === 0) {
    warnings.push('No VLAN information found — config will have minimal content.')
  }
  if (ports.length === 0) {
    warnings.push('No port mapping or edge data found — physical interface config is empty.')
  }

  const vlanConfigContent = buildVlanConfig(vlans)
  const runningConfigContent = buildRunningConfig(device, vlans, ports)

  const vlanResult: ConfigExportResult = {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'cisco-ios-cli',
    filename: `${hostname}-vlan-config.txt`,
    content: vlanConfigContent,
    warnings,
    instructions: INSTRUCTIONS,
  }

  const runningResult: ConfigExportResult = {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'cisco-ios-cli',
    filename: `${hostname}-running-config.txt`,
    content: runningConfigContent,
    warnings,
    instructions: INSTRUCTIONS,
  }

  return [vlanResult, runningResult]
}

/**
 * Convenience single-result entry point. Returns the running config as the
 * primary artifact; the VLAN config is embedded in a comment header.
 */
export function generateCiscoIOS(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult {
  const [vlanResult, runningResult] = generateCiscoIOSConfig(topology, device, profile)
  const hostname = device.data.hostname || 'SWITCH-01'
  const combined =
    '! ═══════════════════════════════════════════\n' +
    `! FILE 1: ${vlanResult.filename}\n` +
    '! ═══════════════════════════════════════════\n' +
    vlanResult.content +
    '\n\n' +
    '! ═══════════════════════════════════════════\n' +
    `! FILE 2: ${runningResult.filename}\n` +
    '! ═══════════════════════════════════════════\n' +
    runningResult.content

  return {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'cisco-ios-cli',
    filename: `${hostname}-ios-config.txt`,
    content: combined,
    warnings: [...new Set([...vlanResult.warnings, ...runningResult.warnings])],
    instructions: INSTRUCTIONS,
  }
}
