import type { TopologySnapshot, DeviceNode, VendorDeviceProfile, ConfigExportResult } from '@gridhive/shared'

const INSTRUCTIONS =
  "Install the Meraki Python SDK: pip install meraki\nEdit API_KEY, ORG_ID, and NETWORK_ID at the top of the script, then run: python3 meraki-config.py"

// ─── helpers ──────────────────────────────────────────────────────────────────

interface VlanInfo {
  id: number
  name: string
  applianceIp: string
  subnet: string
}

interface SsidInfo {
  name: string
  enabled: boolean
  authMode: string
  encryptionMode?: string
  vlanId?: number
}

function cidrSubnet(ip: string, prefix: number): string {
  const parts = ip.split('.').map(Number)
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  const ipInt = ((parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3]) >>> 0
  const net = (ipInt & mask) >>> 0
  const netStr = [
    (net >>> 24) & 0xff,
    (net >>> 16) & 0xff,
    (net >>> 8) & 0xff,
    net & 0xff,
  ].join('.')
  return `${netStr}/${prefix}`
}

function collectVlans(topology: TopologySnapshot, device: DeviceNode): VlanInfo[] {
  const vlanMap = new Map<number, VlanInfo>()

  const addVlan = (id: number, name?: string) => {
    if (vlanMap.has(id)) return
    // Synthesize a plausible applianceIp / subnet
    const thirdOctet = id < 255 ? id : (id % 255)
    const applianceIp = `10.${thirdOctet}.0.1`
    const subnet = `10.${thirdOctet}.0.0/24`
    vlanMap.set(id, { id, name: name || `VLAN${id}`, applianceIp, subnet })
  }

  if (device.data.vlanId) {
    const ip = device.data.ipAddress || '192.168.1.1'
    const prefix = device.data.subnet ? parseInt(device.data.subnet, 10) : 24
    vlanMap.set(device.data.vlanId, {
      id: device.data.vlanId,
      name: device.data.label || `VLAN${device.data.vlanId}`,
      applianceIp: ip,
      subnet: cidrSubnet(ip, prefix),
    })
  }

  if (Array.isArray(device.data.vlanTrunkPorts)) {
    for (const v of device.data.vlanTrunkPorts) addVlan(v)
  }

  if (device.data.portMappings) {
    for (const pm of device.data.portMappings) {
      if (pm.vlanId) addVlan(pm.vlanId)
      if (Array.isArray(pm.trunkVlans)) {
        for (const v of pm.trunkVlans) addVlan(v)
      }
    }
  }

  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    if (Array.isArray(edge.data.trunkVlans)) {
      for (const v of edge.data.trunkVlans) addVlan(v)
    }
    if (edge.data.vlanTag) addVlan(edge.data.vlanTag)
    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    if (neighbor?.data.vlanId) addVlan(neighbor.data.vlanId, neighbor.data.label)
  }

  return Array.from(vlanMap.values()).sort((a, b) => a.id - b.id)
}

function collectSsids(device: DeviceNode): SsidInfo[] {
  const raw = device.data['ssids'] as
    | Array<{ name: string; security?: string; vlanId?: number; enabled?: boolean }>
    | undefined
  if (!raw || !Array.isArray(raw)) return []
  return raw.map(s => ({
    name: s.name,
    enabled: s.enabled !== false,
    authMode: s.security === 'open' ? 'open' : 'psk',
    encryptionMode: s.security === 'open' ? undefined : 'wpa',
    vlanId: s.vlanId,
  }))
}

// ─── Python script builder ────────────────────────────────────────────────────

function indent(n: number, s: string): string {
  const pad = ' '.repeat(n * 4)
  return s
    .split('\n')
    .map(line => (line.trim() ? pad + line : line))
    .join('\n')
}

function pyStr(value: string): string {
  return `'${value.replace(/'/g, "\\'")}'`
}

function buildPythonScript(
  hostname: string,
  vlans: VlanInfo[],
  ssids: SsidInfo[],
): string {
  const lines: string[] = [
    '#!/usr/bin/env python3',
    '"""',
    `Meraki Configuration Script — generated by Gridhive`,
    `Device: ${hostname}`,
    `Generated: ${new Date().toISOString()}`,
    '',
    'Install SDK: pip install meraki',
    '"""',
    'import meraki',
    '',
    '# ── CONFIGURE THESE VALUES ─────────────────────────────────────',
    "API_KEY     = 'your-meraki-api-key'",
    "ORG_ID      = 'your-org-id'",
    "NETWORK_ID  = 'your-network-id'",
    '# ──────────────────────────────────────────────────────────────',
    '',
    'dashboard = meraki.DashboardAPI(API_KEY, suppress_logging=True)',
    '',
  ]

  // VLANs
  if (vlans.length > 0) {
    lines.push('# ── VLANs ──────────────────────────────────────────────────────')
    lines.push("print('Creating VLANs...')")
    for (const vlan of vlans) {
      lines.push('dashboard.appliance.createNetworkApplianceVlan(')
      lines.push(`    networkId=NETWORK_ID,`)
      lines.push(`    id=${vlan.id},`)
      lines.push(`    name=${pyStr(vlan.name)},`)
      lines.push(`    applianceIp=${pyStr(vlan.applianceIp)},`)
      lines.push(`    subnet=${pyStr(vlan.subnet)},`)
      lines.push(`    dhcpHandling='Run a DHCP server',`)
      lines.push(`    dhcpLeaseTime='1 day',`)
      lines.push(`    dnsNameservers='upstream_dns',`)
      lines.push(')')
      lines.push('')
    }
  } else {
    lines.push('# No VLANs detected — add VLAN creation calls here.')
    lines.push('')
  }

  // SSIDs
  if (ssids.length > 0) {
    lines.push('# ── SSIDs ──────────────────────────────────────────────────────')
    lines.push("print('Configuring SSIDs...')")
    for (let i = 0; i < ssids.length; i++) {
      const ssid = ssids[i]
      lines.push('dashboard.wireless.updateNetworkWirelessSsid(')
      lines.push(`    networkId=NETWORK_ID,`)
      lines.push(`    number=${i},`)
      lines.push(`    name=${pyStr(ssid.name)},`)
      lines.push(`    enabled=${ssid.enabled ? 'True' : 'False'},`)
      lines.push(`    authMode=${pyStr(ssid.authMode)},`)
      if (ssid.encryptionMode) {
        lines.push(`    encryptionMode=${pyStr(ssid.encryptionMode)},`)
        lines.push(`    psk='your-psk-here',`)
      }
      if (ssid.vlanId !== undefined) {
        lines.push(`    defaultVlanId=${ssid.vlanId},`)
      }
      lines.push(')')
      lines.push('')
    }
  }

  // Firewall outbound
  lines.push('# ── Firewall L3 — allow all outbound ────────────────────────────')
  lines.push("print('Configuring firewall rules...')")
  lines.push('dashboard.appliance.updateNetworkApplianceFirewallL3FirewallRules(')
  lines.push('    networkId=NETWORK_ID,')
  lines.push('    rules=[')
  lines.push('        {')
  lines.push("            'comment': 'Allow all outbound',")
  lines.push("            'policy': 'allow',")
  lines.push("            'protocol': 'any',")
  lines.push("            'srcPort': 'any',")
  lines.push("            'srcCidr': 'any',")
  lines.push("            'destPort': 'any',")
  lines.push("            'destCidr': 'any',")
  lines.push('        },')
  lines.push('    ],')
  lines.push(')')
  lines.push('')
  lines.push("print('Done. Verify changes in the Meraki Dashboard.')")

  return lines.join('\n')
}

// ─── public API ───────────────────────────────────────────────────────────────

export function generateMeraki(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult {
  const d = device.data
  const hostname = d.hostname || 'meraki-device'
  const warnings: string[] = []

  const vlans = collectVlans(topology, device)
  const ssids = collectSsids(device)

  if (vlans.length === 0) {
    warnings.push('No VLAN information found — VLAN creation block is empty.')
  }
  if (!d.ipAddress) {
    warnings.push('No IP address on device — VLAN appliance IPs are synthesized.')
  }

  const script = buildPythonScript(hostname, vlans, ssids)

  return {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'meraki-api-json',
    filename: `${hostname}-meraki-config.py`,
    content: script,
    warnings,
    instructions: INSTRUCTIONS,
  }
}

indent // suppress unused warning — used internally
