import type { TopologySnapshot, DeviceNode, VendorDeviceProfile, ConfigExportResult } from '@gridhive/shared'

const INSTRUCTIONS =
  "Paste into SonicWall CLI via SSH. Log in as admin, enter 'configure' mode first. " +
  "Run 'commit' and 'exit' when done. Alternatively, import via SonicOS Management > " +
  "Import/Export > Import Settings."

// ─── helpers ──────────────────────────────────────────────────────────────────

function subnetPrefixToMask(prefix: number): string {
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join('.')
}

function deriveNetworkAddress(ip: string, prefix: number): string {
  const parts = ip.split('.').map(Number)
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  const ipInt = ((parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3]) >>> 0
  const net = (ipInt & mask) >>> 0
  return [
    (net >>> 24) & 0xff,
    (net >>> 16) & 0xff,
    (net >>> 8) & 0xff,
    net & 0xff,
  ].join('.')
}

interface VlanInfo {
  id: number
  name: string
  ip: string
  mask: string
  networkAddress: string
}

function collectVlans(topology: TopologySnapshot, device: DeviceNode): VlanInfo[] {
  const vlanMap = new Map<number, VlanInfo>()

  const addVlan = (id: number, name?: string) => {
    if (vlanMap.has(id)) return
    const thirdOctet = id < 255 ? id : (id % 255)
    const ip = `10.${thirdOctet}.0.1`
    vlanMap.set(id, {
      id,
      name: name || `VLAN${id}`,
      ip,
      mask: '255.255.255.0',
      networkAddress: `10.${thirdOctet}.0.0`,
    })
  }

  if (device.data.vlanId) {
    const ip = device.data.ipAddress || '192.168.1.1'
    const prefix = device.data.subnet ? parseInt(device.data.subnet, 10) : 24
    vlanMap.set(device.data.vlanId, {
      id: device.data.vlanId,
      name: `VLAN${device.data.vlanId}`,
      ip,
      mask: subnetPrefixToMask(prefix),
      networkAddress: deriveNetworkAddress(ip, prefix),
    })
  }

  if (Array.isArray(device.data.vlanTrunkPorts)) {
    for (const v of device.data.vlanTrunkPorts) addVlan(v)
  }

  if (device.data.portMappings) {
    for (const pm of device.data.portMappings) {
      if (pm.vlanId) addVlan(pm.vlanId)
      if (Array.isArray(pm.trunkVlans)) {
        for (const v of pm.trunkVlans) addVlan(v)
      }
    }
  }

  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    if (Array.isArray(edge.data.trunkVlans)) {
      for (const v of edge.data.trunkVlans) addVlan(v)
    }
    if (edge.data.vlanTag) addVlan(edge.data.vlanTag)
    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    if (neighbor?.data.vlanId) addVlan(neighbor.data.vlanId, neighbor.data.label)
  }

  return Array.from(vlanMap.values()).sort((a, b) => a.id - b.id)
}

// ─── config builder ───────────────────────────────────────────────────────────

function buildConfig(device: DeviceNode, vlans: VlanInfo[]): string {
  const d = device.data
  const hostname = d.hostname || 'SonicWall'
  const lanIp = d.ipAddress || '192.168.1.1'
  const prefix = d.subnet ? parseInt(d.subnet, 10) : 24
  const lanMask = subnetPrefixToMask(prefix)
  const lanNet = deriveNetworkAddress(lanIp, prefix)

  const lines: string[] = [
    `; SonicWall CLI Configuration — generated by Gridhive`,
    `; Device: ${hostname}`,
    `; Generated: ${new Date().toISOString()}`,
    '; Paste in configure mode. Run "commit" and "exit" to save.',
    ';',
    '',
    '; ── Interface Configuration ──────────────────────────────────',
    `interface X1`,
    ` ip address 0.0.0.0 0.0.0.0 WAN`,
    '',
    `interface X2`,
    ` ip address ${lanIp} ${lanMask} LAN`,
    '',
  ]

  // Sub-interfaces for VLANs
  if (vlans.length > 0) {
    lines.push('; ── VLAN Sub-Interfaces ──────────────────────────────────────')
    for (const vlan of vlans) {
      if (vlan.id === d.vlanId) continue
      lines.push(`interface X2:V${vlan.id}`)
      lines.push(` vlan ${vlan.id}`)
      lines.push(` ip address ${vlan.ip} ${vlan.mask} LAN`)
      lines.push('')
    }
  }

  lines.push('; ── Address Objects ──────────────────────────────────────────')
  lines.push(`network address object "LAN-Subnet"`)
  lines.push(` subnet ${lanNet} ${lanMask}`)
  lines.push('')

  for (const vlan of vlans) {
    if (vlan.id === d.vlanId) continue
    lines.push(`network address object "${vlan.name}-Subnet"`)
    lines.push(` subnet ${vlan.networkAddress} ${vlan.mask}`)
    lines.push('')
  }

  lines.push('; ── DHCP Server ───────────────────────────────────────────────')
  const dhcpParts = lanIp.split('.').map(Number)
  lines.push('ip dhcp server')
  lines.push(` interface X2`)
  lines.push(` subnet ${lanNet} ${lanMask}`)
  lines.push(` default-gateway ${lanIp}`)
  lines.push(` dns-server 8.8.8.8`)
  lines.push(` lease-time 86400`)
  lines.push(
    ` range ${dhcpParts[0]}.${dhcpParts[1]}.${dhcpParts[2]}.10 ${dhcpParts[0]}.${dhcpParts[1]}.${dhcpParts[2]}.254`,
  )
  lines.push('')

  lines.push('; ── Access Rules ─────────────────────────────────────────────')
  lines.push(`ip access-rule LAN WAN allow "Allow-LAN-to-WAN"`)
  lines.push(` source any`)
  lines.push(` destination any`)
  lines.push(` service any`)
  lines.push(` comment "Allow all outbound from LAN"`)
  lines.push('')
  lines.push(`ip access-rule WAN LAN deny "Deny-WAN-to-LAN"`)
  lines.push(` source any`)
  lines.push(` destination any`)
  lines.push(` service any`)
  lines.push(` comment "Deny inbound from WAN"`)
  lines.push('')

  lines.push('; ── NAT Policy ───────────────────────────────────────────────')
  lines.push(`nat policy "LAN-to-WAN-NAT"`)
  lines.push(` original-source "LAN-Subnet"`)
  lines.push(` translated-source interface X1`)
  lines.push(` inbound-interface X2`)
  lines.push(` outbound-interface X1`)

  return lines.join('\n')
}

// ─── public API ───────────────────────────────────────────────────────────────

export function generateSonicWall(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult {
  const d = device.data
  const hostname = d.hostname || 'SonicWall'
  const warnings: string[] = []

  const vlans = collectVlans(topology, device)

  if (!d.ipAddress) {
    warnings.push('No IP address on device — defaulted LAN to 192.168.1.1/24.')
  }
  if (vlans.length === 0) {
    warnings.push('No VLAN information found — only primary LAN interface generated.')
  }

  const content = buildConfig(device, vlans)

  return {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'sonicwall-exp',
    filename: `${hostname}-sonicwall-config.txt`,
    content,
    warnings,
    instructions: INSTRUCTIONS,
  }
}
