import type { TopologySnapshot, DeviceNode, VendorDeviceProfile, ConfigExportResult } from '@gridhive/shared'

const INSTRUCTIONS =
  "Open WatchGuard System Manager > Policy Manager > File > Import. " +
  "Select the generated .xml file. Review policies before activating."

// ─── helpers ──────────────────────────────────────────────────────────────────

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function subnetPrefixToMask(prefix: number): string {
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join('.')
}

function deriveNetworkAddress(ip: string, prefix: number): string {
  const parts = ip.split('.').map(Number)
  const mask = (0xffffffff << (32 - prefix)) >>> 0
  const ipInt = ((parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3]) >>> 0
  const net = (ipInt & mask) >>> 0
  return [
    (net >>> 24) & 0xff,
    (net >>> 16) & 0xff,
    (net >>> 8) & 0xff,
    net & 0xff,
  ].join('.')
}

function cidr(ip: string, prefix: number): string {
  const net = deriveNetworkAddress(ip, prefix)
  return `${net}/${prefix}`
}

interface VlanInfo {
  id: number
  name: string
  ip: string
  prefix: number
}

function collectVlans(topology: TopologySnapshot, device: DeviceNode): VlanInfo[] {
  const vlanMap = new Map<number, VlanInfo>()

  const addVlan = (id: number, name?: string) => {
    if (vlanMap.has(id)) return
    const thirdOctet = id < 255 ? id : (id % 255)
    vlanMap.set(id, { id, name: name || `VLAN${id}`, ip: `10.${thirdOctet}.0.1`, prefix: 24 })
  }

  if (device.data.vlanId) {
    const ip = device.data.ipAddress || '192.168.1.1'
    const prefix = device.data.subnet ? parseInt(device.data.subnet, 10) : 24
    vlanMap.set(device.data.vlanId, { id: device.data.vlanId, name: `VLAN${device.data.vlanId}`, ip, prefix })
  }

  if (Array.isArray(device.data.vlanTrunkPorts)) {
    for (const v of device.data.vlanTrunkPorts) addVlan(v)
  }

  if (device.data.portMappings) {
    for (const pm of device.data.portMappings) {
      if (pm.vlanId) addVlan(pm.vlanId)
      if (Array.isArray(pm.trunkVlans)) {
        for (const v of pm.trunkVlans) addVlan(v)
      }
    }
  }

  for (const edge of topology.edges) {
    const isConnected = edge.source === device.id || edge.target === device.id
    if (!isConnected) continue
    if (Array.isArray(edge.data.trunkVlans)) {
      for (const v of edge.data.trunkVlans) addVlan(v)
    }
    if (edge.data.vlanTag) addVlan(edge.data.vlanTag)
    const neighborId = edge.source === device.id ? edge.target : edge.source
    const neighbor = topology.nodes.find(n => n.id === neighborId)
    if (neighbor?.data.vlanId) addVlan(neighbor.data.vlanId, neighbor.data.label)
  }

  return Array.from(vlanMap.values()).sort((a, b) => a.id - b.id)
}

// ─── XML builder ──────────────────────────────────────────────────────────────

function buildXml(device: DeviceNode, vlans: VlanInfo[]): string {
  const d = device.data
  const hostname = escapeXml(d.hostname || 'Firebox')
  const lanIp = d.ipAddress || '192.168.1.1'
  const prefix = d.subnet ? parseInt(d.subnet, 10) : 24
  const lanMask = subnetPrefixToMask(prefix)
  const lanCidr = cidr(lanIp, prefix)
  const dhcpParts = lanIp.split('.').map(Number)
  const dhcpFrom = `${dhcpParts[0]}.${dhcpParts[1]}.${dhcpParts[2]}.10`
  const dhcpTo = `${dhcpParts[0]}.${dhcpParts[1]}.${dhcpParts[2]}.254`

  // Build extra VLAN interfaces
  let extraInterfaces = ''
  let extraDhcp = ''
  let extraAliases = ''
  for (const vlan of vlans) {
    if (vlan.id === d.vlanId) continue
    const vname = escapeXml(vlan.name)
    const vCidr = cidr(vlan.ip, vlan.prefix)
    const vParts = vlan.ip.split('.').map(Number)
    const vFrom = `${vParts[0]}.${vParts[1]}.${vParts[2]}.10`
    const vTo = `${vParts[0]}.${vParts[1]}.${vParts[2]}.254`

    extraInterfaces += `
    <interface name="${vname}">
      <vlan-id>${vlan.id}</vlan-id>
      <static-ip>${vCidr}</static-ip>
    </interface>`

    extraDhcp += `
    <dhcp-server>
      <interface>${vname}</interface>
      <ip-range from="${vFrom}" to="${vTo}"/>
      <dns-server>8.8.8.8</dns-server>
      <gateway>${vlan.ip}</gateway>
      <netmask>${subnetPrefixToMask(vlan.prefix)}</netmask>
      <lease-time>86400</lease-time>
    </dhcp-server>`

    extraAliases += `
    <alias name="Any-${vname}">
      <member>${vCidr}</member>
    </alias>`
  }
  void lanMask

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  WatchGuard Fireware Configuration — generated by Gridhive
  Device: ${hostname}
  Generated: ${new Date().toISOString()}
  Import via: System Manager > Policy Manager > File > Import
-->
<profile xmlns="http://www.watchguard.com/schema/profile.xsd"
         major-version="12" minor-version="10">

  <device-name>${hostname}</device-name>

  <feature name="interface-all">
    <interface name="External">
      <static-ip>0.0.0.0/0</static-ip>
      <role>external</role>
    </interface>
    <interface name="Trusted">
      <static-ip>${lanCidr}</static-ip>
      <role>trusted</role>
    </interface>${extraInterfaces}
  </feature>

  <feature name="dhcp">
    <dhcp-server>
      <interface>Trusted</interface>
      <ip-range from="${dhcpFrom}" to="${dhcpTo}"/>
      <dns-server>8.8.8.8</dns-server>
      <dns-server>8.8.4.4</dns-server>
      <gateway>${lanIp}</gateway>
      <netmask>${subnetPrefixToMask(prefix)}</netmask>
      <lease-time>86400</lease-time>
    </dhcp-server>${extraDhcp}
  </feature>

  <feature name="alias">
    <alias name="Any-Trusted">
      <member>${lanCidr}</member>
    </alias>
    <alias name="Any-External">
      <member>0.0.0.0/0</member>
    </alias>${extraAliases}
  </feature>

  <feature name="policy">
    <policy name="Outbound" policy-type="allow" log="true">
      <from><alias>Any-Trusted</alias></from>
      <to><alias>Any-External</alias></to>
      <service-list>Any</service-list>
      <nat>dynamic</nat>
    </policy>
    <policy name="Deny-Inbound" policy-type="deny" log="true">
      <from><alias>Any-External</alias></from>
      <to><alias>Any-Trusted</alias></to>
      <service-list>Any</service-list>
    </policy>
  </feature>

</profile>
`
}

// ─── public API ───────────────────────────────────────────────────────────────

export function generateWatchGuard(
  topology: TopologySnapshot,
  device: DeviceNode,
  profile: VendorDeviceProfile,
): ConfigExportResult {
  const d = device.data
  const hostname = d.hostname || 'Firebox'
  const warnings: string[] = []

  const vlans = collectVlans(topology, device)

  if (!d.ipAddress) {
    warnings.push('No IP address on device — defaulted Trusted interface to 192.168.1.1/24.')
  }
  if (vlans.length === 0) {
    warnings.push('No VLAN information found — only Trusted and External interfaces generated.')
  }

  const content = buildXml(device, vlans)

  return {
    deviceId: device.id,
    vendor: profile.vendor,
    format: 'watchguard-xml',
    filename: `${hostname}-watchguard-config.xml`,
    content,
    warnings,
    instructions: INSTRUCTIONS,
  }
}
