import type { VendorDeviceProfile } from '../../types/vendors.js'

const baseReaderSchema = {
  sections: [
    {
      id: 'device-settings',
      title: 'Device Settings',
      description: 'Basic device configuration for the reader',
      fields: [
        {
          key: 'device_name',
          label: 'Device Name',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'ip_address',
          label: 'IP Address',
          type: 'ip' as const,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'subnet_mask',
          label: 'Subnet Mask',
          type: 'text' as const,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'controller_port',
          label: 'Controller Port',
          type: 'number' as const,
          defaultValue: 3001,
          required: false,
          affectsConfigOutput: true,
        },
      ],
    },
  ],
}

const baseControllerSchema = {
  sections: [
    {
      id: 'device-settings',
      title: 'Device Settings',
      description: 'Basic device configuration for the controller',
      fields: [
        {
          key: 'device_name',
          label: 'Device Name',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'ip_address',
          label: 'IP Address',
          type: 'ip' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'subnet_mask',
          label: 'Subnet Mask',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'controller_port',
          label: 'Controller Port',
          type: 'number' as const,
          defaultValue: 3001,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'encryption_enabled',
          label: 'Encryption Enabled',
          type: 'boolean' as const,
          defaultValue: true,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'osdp_address',
          label: 'OSDP Address',
          type: 'number' as const,
          required: false,
          affectsConfigOutput: true,
        },
      ],
    },
  ],
}

export const hidGlobalDevices: VendorDeviceProfile[] = [
  // --- Readers ---
  {
    id: 'hid-r10',
    vendor: 'hid-global',
    productLine: 'HID Reader',
    model: 'R10',
    displayName: 'HID R10 Multi-Technology Reader',
    deviceType: 'ac-reader',
    icon: 'ac-reader',
    specs: {},
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    ndaaCompliant: true,
    notes: 'OSDP v2 and Wiegand interface. Multi-technology: iCLASS SE, SEOS, MIFARE. credentialTypes: prox-card, smart-card. readerProtocol: osdp, wiegand.',
  },
  {
    id: 'hid-r40',
    vendor: 'hid-global',
    productLine: 'HID Reader',
    model: 'R40',
    displayName: 'HID R40 iCLASS SE Reader',
    deviceType: 'ac-reader',
    icon: 'ac-reader',
    specs: {},
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2021,
    ndaaCompliant: true,
    notes: 'OSDP v2. iCLASS SE, SEOS, MIFARE DESFire EV2. Compact form factor. credentialTypes: smart-card. readerProtocol: osdp.',
  },
  {
    id: 'hid-r90',
    vendor: 'hid-global',
    productLine: 'HID Reader',
    model: 'R90',
    displayName: 'HID R90 Biometric Reader',
    deviceType: 'ac-biometric',
    icon: 'ac-biometric',
    specs: {},
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2021,
    ndaaCompliant: true,
    notes: 'OSDP v2. Biometric fingerprint + smart-card combo reader. credentialTypes: biometric-fp, smart-card. readerProtocol: osdp.',
  },
  {
    id: 'hid-signo-10',
    vendor: 'hid-global',
    productLine: 'HID Signo',
    model: 'Signo 10',
    displayName: 'HID Signo 10 Reader',
    deviceType: 'ac-reader',
    icon: 'ac-reader',
    specs: {},
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2022,
    ndaaCompliant: true,
    notes: 'OSDP v2. iCLASS Seos, MIFARE DESFire, BLE. Ultra-slim design. credentialTypes: smart-card, mobile-ble, mobile-nfc. readerProtocol: osdp.',
  },
  {
    id: 'hid-signo-20',
    vendor: 'hid-global',
    productLine: 'HID Signo',
    model: 'Signo 20',
    displayName: 'HID Signo 20 Reader with PIN Pad',
    deviceType: 'ac-key-pad',
    icon: 'ac-key-pad',
    specs: {},
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2022,
    ndaaCompliant: true,
    notes: 'OSDP v2. Full multi-technology reader with built-in PIN pad. credentialTypes: smart-card, mobile-ble, mobile-nfc, pin, pin-and-card. readerProtocol: osdp.',
  },
  {
    id: 'hid-signo-40b',
    vendor: 'hid-global',
    productLine: 'HID Signo',
    model: 'Signo 40B',
    displayName: 'HID Signo 40B Biometric Reader',
    deviceType: 'ac-biometric',
    icon: 'ac-biometric',
    specs: {
      formFactor: 'outdoor',
    },
    configSchema: baseReaderSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2022,
    ndaaCompliant: true,
    notes: 'OSDP v2. Biometric fingerprint + smart-card. IP65 outdoor rated. credentialTypes: biometric-fp, smart-card, mobile-ble, mobile-nfc. readerProtocol: osdp.',
  },

  // --- Controllers ---
  {
    id: 'hid-vertx-v100',
    vendor: 'hid-global',
    productLine: 'HID VertX',
    model: 'VertX V100',
    displayName: 'HID VertX V100 1-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 1,
      readerPorts: 2,
    },
    configSchema: baseControllerSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2019,
    ndaaCompliant: true,
    notes: '1-door IP-based controller. OSDP and Wiegand reader ports. 2 reader ports. controllerProtocol: wiegand.',
  },
  {
    id: 'hid-vertx-v200',
    vendor: 'hid-global',
    productLine: 'HID VertX',
    model: 'VertX V200',
    displayName: 'HID VertX V200 2-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 2,
      readerPorts: 4,
      inputPorts: 16,
      outputPorts: 4,
    },
    configSchema: baseControllerSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2019,
    ndaaCompliant: true,
    notes: '2-door controller. 4 reader ports, 16 inputs, 4 outputs. controllerProtocol: wiegand.',
  },
  {
    id: 'hid-vertx-v1000',
    vendor: 'hid-global',
    productLine: 'HID VertX',
    model: 'VertX V1000',
    displayName: 'HID VertX V1000 Central Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 64,
    },
    configSchema: baseControllerSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    ndaaCompliant: true,
    notes: 'Central controller. 64-door capacity via EVO modules. controllerProtocol: osdp.',
  },
  {
    id: 'hid-edge-evo-solo',
    vendor: 'hid-global',
    productLine: 'HID Edge EVO',
    model: 'Edge EVO Solo',
    displayName: 'HID Edge EVO Solo Reader-Integrated Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 1,
    },
    configSchema: baseControllerSchema,
    configFormat: 'generic-summary',
    firmwareVersions: ['latest'],
    releaseYear: 2021,
    ndaaCompliant: true,
    notes: 'Reader-integrated 1-door controller. PoE powered. 512MB onboard storage. controllerProtocol: osdp.',
  },
]
