import type { VendorDeviceProfile } from '../../types/vendors.js'

const baseServerSchema = {
  sections: [
    {
      id: 'device-settings',
      title: 'Device Settings',
      description: 'Basic device configuration for the access control server',
      fields: [
        {
          key: 'device_name',
          label: 'Device Name',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'ip_address',
          label: 'IP Address',
          type: 'ip' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'subnet_mask',
          label: 'Subnet Mask',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'controller_port',
          label: 'Controller Port',
          type: 'number' as const,
          defaultValue: 3001,
          required: false,
          affectsConfigOutput: true,
        },
      ],
    },
  ],
}

const baseControllerSchema = {
  sections: [
    {
      id: 'device-settings',
      title: 'Device Settings',
      description: 'Basic device configuration for the controller',
      fields: [
        {
          key: 'device_name',
          label: 'Device Name',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'ip_address',
          label: 'IP Address',
          type: 'ip' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'subnet_mask',
          label: 'Subnet Mask',
          type: 'text' as const,
          required: true,
          affectsConfigOutput: true,
        },
        {
          key: 'controller_port',
          label: 'Controller Port',
          type: 'number' as const,
          defaultValue: 3001,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'encryption_enabled',
          label: 'Encryption Enabled',
          type: 'boolean' as const,
          defaultValue: true,
          required: false,
          affectsConfigOutput: true,
        },
        {
          key: 'osdp_address',
          label: 'OSDP Address',
          type: 'number' as const,
          required: false,
          affectsConfigOutput: true,
        },
      ],
    },
  ],
}

export const lenelS2Devices: VendorDeviceProfile[] = [
  // --- Software / Servers ---
  {
    id: 'lenel-onguard-server',
    vendor: 'lenel-s2',
    productLine: 'LenelS2 OnGuard',
    model: 'OnGuard Server',
    displayName: 'LenelS2 OnGuard Access Control Server',
    deviceType: 'ac-server',
    icon: 'ac-server',
    specs: {},
    configSchema: baseServerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    notes: 'Windows Server-based enterprise access control platform. Unlimited doors (licensed). acPlatform: lenel-onguard.',
  },
  {
    id: 'lenel-elements-cloud',
    vendor: 'lenel-s2',
    productLine: 'LenelS2 Elements',
    model: 'Elements Cloud',
    displayName: 'LenelS2 Elements Cloud Access Control',
    deviceType: 'ac-server',
    icon: 'ac-server',
    specs: {
      cloudManaged: true,
      maxDoors: 64,
    },
    configSchema: baseServerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2022,
    notes: 'Cloud-hosted access control. Max 64 readers per site. 5k events per day. acPlatform: lenel-elements. cloudManaged: true.',
  },
  {
    id: 'lenel-s2-netbox',
    vendor: 'lenel-s2',
    productLine: 'S2 NetBox',
    model: 'NetBox',
    displayName: 'S2 NetBox Web-Based Access Control',
    deviceType: 'ac-server',
    icon: 'ac-server',
    specs: {
      maxDoors: 128,
    },
    configSchema: baseServerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    notes: 'Web-based appliance or VM deployment. 128 doors standard capacity. acPlatform: s2-netbox.',
  },

  // --- Controllers ---
  {
    id: 'lenel-ngp-1501',
    vendor: 'lenel-s2',
    productLine: 'LenelS2 NGP',
    model: 'NGP-1501',
    displayName: 'LenelS2 NGP-1501 1-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 1,
    },
    configSchema: baseControllerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2021,
    notes: '1-door Mercury NGP panel. Encrypted communications, tamper detection. controllerProtocol: mercury.',
  },
  {
    id: 'lenel-ngp-1502',
    vendor: 'lenel-s2',
    productLine: 'LenelS2 NGP',
    model: 'NGP-1502',
    displayName: 'LenelS2 NGP-1502 2-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 2,
    },
    configSchema: baseControllerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2021,
    notes: '2-door Mercury NGP panel. controllerProtocol: mercury.',
  },
  {
    id: 'mercury-ep-1502',
    vendor: 'lenel-s2',
    productLine: 'Mercury EP',
    model: 'EP-1502',
    displayName: 'Mercury EP-1502 2-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 2,
    },
    configSchema: baseControllerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    notes: '2-door Mercury EP open-platform panel. Multi-vendor compatible. controllerProtocol: mercury.',
  },
  {
    id: 'mercury-ep-2500',
    vendor: 'lenel-s2',
    productLine: 'Mercury EP',
    model: 'EP-2500',
    displayName: 'Mercury EP-2500 32-Door Controller',
    deviceType: 'ac-controller',
    icon: 'ac-controller',
    specs: {
      maxDoors: 32,
    },
    configSchema: baseControllerSchema,
    configFormat: 'ac-implementation-guide',
    firmwareVersions: ['latest'],
    releaseYear: 2020,
    notes: '32-door Mercury LP large-facility panel. Designed for large enterprise deployments. controllerProtocol: mercury.',
  },
]
